### ISSUE TITLE
Unable to build the project with a fresh XCode installation and a fresh copy of the repo

### ISSUE THREAD

**Issue by norbertpotocki** [davidsansome/tsurukame#101]
Hi @davidsansome,

I'm trying to build the app by following instructions from the README file. Unfortunately there's a number of import errors that immediately pop up (see one below). Could you help me resolve those? I imagine there are some extra setup steps that I missed.

```
error: Build input files cannot be found: '/Users/test/tsurukame/ios/third_party/Charts/Data/Implementations/Standard/ChartDataSet.swift'
```

XCode 10.1
Simulator: iOS 12.1

**Comment by davidsansome** [comment]
Oops sorry about that.  I had "data" in the .gitignore to hide the data directory in the root of the repo, but that was also hiding the Charts/Data/... files.
