### ISSUE TITLE
Can't login due to error in fetching API

### ISSUE THREAD

**Issue by aimylee** [davidsansome/tsurukame#105]
Hi! I've tried uninstalling and reinstalling the app but to no avail. I've also regenerated the API key too.

**Comment by kcomandich** [comment]
I have the same problem, "An error occurred fetching your API key".

Is it because the API keys are no longer on the https://www.wanikani.com/settings/account page, but on https://www.wanikani.com/settings/personal_access_tokens instead?

Thanks!

**Comment by Sereni** [comment]
+1, same problem

**Comment by chetwatkins** [comment]
+1, also having this issue. Love the tool and hope to be able to use it again soon. Thanks!

**Comment by davidsansome** [comment]
> Is it because the API keys are no longer on the https://www.wanikani.com/settings/account page, but on https://www.wanikani.com/settings/personal_access_tokens instead?

Yep that's exactly it.  I've got a fix coming soon...
