### ISSUE TITLE
Scraper fails

### ISSUE THREAD

**Issue by onimitch** [davidsansome/tsurukame#107]
I get a couple of diff issues trying to run the scraper:

1. Fetching https://www.wanikani.com/json/radical/1
Error getting radical 1: invalid character '<' looking for beginning of value

2. Fetching https://www.wanikani.com/json/radical/140
Error getting radical 140: Request for https://www.wanikani.com/json/radical/140 failed: HTTP 429 Too Many Requests

**Comment by onimitch** [comment]
Is the scraper data.bin still required?

**Comment by onimitch** [comment]
This can be closed, it was due to an expired cookie.

**Comment by jcousins-ynap** [comment]
I also found that copying the cookie from `preview.wanikani.com` doesn't work some of the time.
