### ISSUE TITLE
Missing reviews

### ISSUE THREAD

**Issue by andresovela** [davidsansome/tsurukame#116]
Ever since I discovered Tsurukame I stopped using Wanikani in web. Today I opened the website and noticed that I had 19 pending reviews while the app showed zero.

I did the reviews and noticed how they hadn't appeared in a really long time. There were radicals, kanji and vocabs. I didn't notice any patterns.

This is a screenshot of the items that don't appear in Tsurukame. Hope it helps.

<img width="573" alt="Screen Shot 2019-04-18 at 15 42 24" src="https://user-images.githubusercontent.com/8990961/56365224-9a488500-61f0-11e9-9c63-2c2f30035a99.png">

**Comment by andresovela** [comment]
After doing the reviews on the web, the missing items started appearing again in the review queue in Tsurukame.

**Comment by turtlemaster19** [comment]
Weird. Have you experienced this again? Those reviews were fine for me in Tsurukame - I actually learned them there. Did you refresh the app before doing the reviews on the web (by swiping your finger downward until the loading circle appears?

**Comment by andresovela** [comment]
It hasn't happened since then I think. There were a couple of app updates in the last months so the issue might have been fixed already. I'll close the issue.
