### ISSUE TITLE
Keyboard shortcut to show default font

### ISSUE THREAD

**Issue by lyallcooper** [davidsansome/tsurukame#117]
When using the font randomization feature, one can tap + hold on the review screen to temporarily reveal the item in the default font. It’d be great if there were a keyboard shortcut (e.g. control or option) for this too.

**Comment by turtlemaster19** [comment]
This was resolved in the above PR. I can confirm that tab does do this.

**Comment by lyallcooper** [comment]
Thanks, I should’ve closed this when my PR was merged.
