### ISSUE TITLE
Show a more helpful error when answering with big-kana instead of small-kana

### ISSUE THREAD

**Issue by HackF0x** [davidsansome/tsurukame#125]
![95D97163-D0DC-43AE-B442-2843ADCD5AF7](https://user-images.githubusercontent.com/34410028/58190813-4d424d80-7c8b-11e9-8b98-80fc5acc6f52.png)

I’ve ran into a few quiz items that state they are incorrect when they are not. I’ve even tried copying and pasting the reading.

**Comment by davidsansome** [comment]
It looks like you're typing the big-yu (ゆ) not the little-yu (ゅ).
If you're using an English keyboard you need to type "nyuu" (not "niyuu") to get にゅう.  If you're using a Japanese keyboard you need to press the 小 button after typing the ゆ.

See https://community.wanikani.com/t/what-did-i-do-wrong/29984/2 for more info.

This mistake is pretty common for beginners so maybe Tsurukame should detect it and show a more helpful error message.

**Comment by HackF0x** [comment]
Oh heck. You are absolutely right. Closing issue.
