### ISSUE TITLE
App uses Chinese characters for some kanji when device language preferences do not include Japanese

### ISSUE THREAD

**Issue by rubyroobs** [davidsansome/tsurukame#127]
I've noticed that strangely the iPad version of the app shows Chinese characters for same kanji for example it displays 入る instead of 入る. What's weirder was my iPhone (both on latest iOS/tsurukame) did not have this issue.

![Image of iPhone XS Max with no issue](https://i.imgur.com/8Oss0LH.png)
![Image of iPad Pro with issue](https://i.imgur.com/JxcFaoB.png)

While writing this as a bug report, I resolved this by setting Japanese as the 2nd language on my iPad (the only difference I found between my iPad and my iPhone). I imagine this is iOS defaulting to Chinese over Japanese - it might be useful to other users to enforce this at the app level if possible, or add this to the documentation?

**Comment by davidsansome** [comment]
Thanks for this bug report!
I didn't even realise han characters could be rendered differently depending on the user's second language.
I've tried to fix this by explicitly using the iOS Japanese font (Hiragino Sans) in each place Japanese text is shown.  I might've missed some though.

**Comment by osdiab** [comment]
Yeah I just noticed this was happening for the character 直 when I didn’t have any other languages besides English selected, resolved by including Japanese as a system language. Perhaps should tell the user at some point to do that

![52FC6889-8F59-4F94-A7B7-4BFF947949A9](https://user-images.githubusercontent.com/1890926/61573634-f0c5a800-aaec-11e9-9278-ad6429400e1a.png)
![302D7BB3-51F2-4555-B661-BF91ADB1DB30](https://user-images.githubusercontent.com/1890926/61573635-f15e3e80-aaec-11e9-84b7-4cbf233c603f.png)
