### ISSUE TITLE
Background audio ducked on switching to app

### ISSUE THREAD

**Issue by indirect** [davidsansome/tsurukame#130]
While doing reviews, simply switching into the app causes the background audio to get quieter. Only after playing a reading does the volume return to normal, with the background audio reduced only during reading playback from that point forward.

**Comment by indirect** [comment]
A small update on this: I noticed that if you immediately switch out of the app, it un-ducks, and you can then switch back to the app without the sound getting ducked again.

**Comment by lyallcooper** [comment]
Probably related to something I didn't do quite right in #124 😅
