### ISSUE TITLE
It runs on macOS 10.15! :D

### ISSUE THREAD

**Issue by indirect** [davidsansome/tsurukame#132]
<img width="1280" alt="Screen Shot 2019-06-05 at 12 46 24 PM" src="https://user-images.githubusercontent.com/78/58985770-f52e3f80-8790-11e9-8a60-c85f92b53af4.png">

reviews need a little UI work though 😂 

<img width="901" alt="image" src="https://user-images.githubusercontent.com/78/58985800-037c5b80-8791-11e9-87af-1956c853edd0.png">

**Comment by indirect** [comment]
Update on macOS builds: macOS 10.15 b4 seems to have fixed the last of the alignment bugs, and I should have a build that people can try out soon if they are comfortable running a beta OS known to destroy iCloud data at random. 😅

**Comment by indirect** [comment]
http://files.arko.net/63a4ecbabd0e/Tsurukame.zip

**Comment by grobmeier** [comment]
@indirect This is awesome news. Instead of downloading a ZIP, can I somehow git pull and compile your stuff? I got xcode running, but have no clue on osx development - a readme is appreciated

**Comment by indirect** [comment]
@grobmeier the zip is me compiling the master branch with macOS turned on, there’s nothing to pull.

**Comment by turtlemaster19** [comment]
This seems awesome. This should be added and released in the App Store.

**Comment by sciencemanx** [comment]
I think it would be nice to polish a bit before putting it onto the App Store (add more mac specific layout as makes sense), but maybe the value to people having it now would outweigh the current awkwardness of the iOS layout on mac.

**Comment by turtlemaster19** [comment]
UPDATE: macOS 10.15 is stable now ;)
Maybe we should consider doing this, even without any Mac-specific changes, because the ability to review offline with those scripts, like was stated above, could be useful.

**Comment by indirect** [comment]
Feel free to send a PR!

**Comment by turtlemaster19** [comment]
@indirect PR merged. Can we close this?

**Comment by turtlemaster19** [comment]
Speaking of this, @davidsansome, can you release this to the Mac App Store next update?
