### ISSUE TITLE
Missing kanji from level 18

### ISSUE THREAD

**Issue by jdbish** [davidsansome/tsurukame#133]
Hello! I am loving the app. However, I am doing level 18 and there are three kanji that for some reason don’t seem to exist: strike, throat, and candy. I have to go into the mobile website to see or complete those reviews.

**Comment by bmironer** [comment]
They are part of the latest update it seems.
https://community.wanikani.com/t/wanikani-content-update-june-3-2019/37043

**Comment by lyallcooper** [comment]
Another update came in—so more missing items https://community.wanikani.com/t/wanikani-content-update-july-25-2019

**Comment by bmironer** [comment]
These are now part of the 1.11 release
