### ISSUE TITLE
Lessons create invalid reviews?

### ISSUE THREAD

**Issue by indirect** [davidsansome/tsurukame#137]
After doing 5 lessons, the main screen shows 5 reviews waiting to upload, and the console shows trying to post the lesson as a review:

> 2019-07-07 18:22:46.815460-0700 Tsurukame[1112:258150] POST {"review":{"incorrect_reading_answers":0,"assignment_id":140620663,"incorrect_meaning_answers":0}} to https://api.wanikani.com/v2/reviews/
> 2019-07-07 18:24:43.561362-0700 Tsurukame[1112:258169] Error Error Domain=kTKMClientErrorDomain Code=422 "Record invalid" UserInfo={kTKMClientErrorResponseKey=<NSHTTPURLResponse: 0x2830dd620> { URL: https://api.wanikani.com/v2/reviews/ } { Status Code: 422, Headers {
> [...]

Is this new? Maybe the WKv2 API just updated to require you to hit the [Start an Assignment](https://docs.api.wanikani.com/20170710/#start-an-assignment) endpoint, which hasn't previously been required?

**Comment by davidsansome** [comment]
Thanks for spotting this!  Yeah it looks like we need to use that new endpoint now :/

**Comment by indirect** [comment]
That was so fast! I'm glad I didn't keep poking at it. 😂
