### ISSUE TITLE
Locked kanji on level 6

### ISSUE THREAD

**Issue by ianklatzco** [davidsansome/tsurukame#141]
Hiya,

I noticed some kanji that I couldn't see in Tsurukame, only via the wanikani website.

Notice the 6 Apprentice Kanji:

![photo_2019-07-15_14-45-35](https://user-images.githubusercontent.com/1487413/61251470-6b6a7e00-a70f-11e9-8d6f-dfa8ed5f13f4.jpg)

But they actually appear locked and do not show in lessons via tsurukame:

![photo_2019-07-15_14-45-45](https://user-images.githubusercontent.com/1487413/61251504-7c1af400-a70f-11e9-8f9a-1220bea5b56b.jpg)

Even though, via the web ui, they are not locked / are available in reviews:

![photo_2019-07-15_14-45-54](https://user-images.githubusercontent.com/1487413/61251516-863cf280-a70f-11e9-94c2-fc0acbfd985d.jpg)

![photo_2019-07-15_14-45-49](https://user-images.githubusercontent.com/1487413/61251526-8c32d380-a70f-11e9-9bc8-5980f7b666bd.jpg)

I've exported the .db, but I'm unsure if it should be kept private (I didn't see anything sensitive upon a quick browse). Please let me know if you need it / if it should be emailed instead of posted here.

**Comment by ianklatzco** [comment]
Thank you for this app! I really appreciate it c:

**Comment by davidsansome** [comment]
Interesting!  Can you email the database to me (me@davidsansome.com)?  It's probably best you don't post it here since it might contain HTTP logs with your cookie or API key.

After that, try logging out and logging back in again in the app's settings menu.

**Comment by ianklatzco** [comment]
Will do when I have a moment @ my PC! I tried logging in/out, but it didn’t solve the issue.

I did the lessons on the web client and that moved the kanji to the correct status in Tsurukame.

**Comment by turtlemaster19** [comment]
I had this issue as well - these kanji, radicals, (and probably vocab) don't show up in reviews until synced with WK. These are items that lessons have happened to offline.

**Comment by turtlemaster19** [comment]
My issue must have been #87 - is this the same issue?

**Comment by turtlemaster19** [comment]
@ianklatzco Is this the same as #87, or a resolved issue?

**Comment by ianklatzco** [comment]
the same!

**Comment by turtlemaster19** [comment]
@ianklatzco Great! Can you close it then to not crowd out the issues list?
