### ISSUE TITLE
Leveling up before completing lessons

### ISSUE THREAD

**Issue by dreams4ever25** [davidsansome/tsurukame#156]
Perhaps this is expected behavior but to me it seems strange: I will advance in level once new lessons are "unlocked" but not before they are reviewed.

This results in advancing in level before clearing the previous level's items. Meaning I can have 160 lessons in the qeue, not have studied all lessons for the current level, but the system bumping me to the next level. 

I feel like a cheat, advancing without actually earning it. :(

Preferred behavior: advance in level once all lessons are reviewed for that level. Unlocking doesn't do anything to my current level status.

**Comment by indirect** [comment]
@dreams4ever25 this app has nothing to do with that. WaniKani is leveling you up, and the app is just reporting it. You'll see the same thing if you use the website.

**Comment by dreams4ever25** [comment]
@indirect Ah, just goes to show how much I love Tsurukame and rarely use the website these days. Thanks for the heads-up and kudos for a fantastic app!
