### ISSUE TITLE
All items missing audio

### ISSUE THREAD

**Issue by lyallcooper** [davidsansome/tsurukame#158]
On later master (2c642c2b), the audio play button is missing on vocabulary item pages. The audio also doesn’t autoplay during reviews. 

On an iPhone X running the iOS 13 public beta 5.

Ex:
![96201B94-914A-475E-8F6D-C7F793A06382](https://user-images.githubusercontent.com/894902/63072110-e8d40a80-bed6-11e9-9243-72c4b83b8b73.jpeg)

**Comment by davidsansome** [comment]
We changed the way we store audio IDs in the data.bin - you'll need to recreate it.
It now supports multiple audio files for each item, and will pick one at random each time.

**Comment by lyallcooper** [comment]
Ah make sense, thank you!
