### ISSUE TITLE
Terms with dashes unsolvable

### ISSUE THREAD

**Issue by Userliam7** [davidsansome/tsurukame#160]
Any review/lesson that contains a dash (ー), examples include ハート形、迷惑メール、etc. cannot be solved

**Comment by Ulakanakulot** [comment]
Had the same issue with ハート形 just now.

**Comment by zapan** [comment]
Same here with ビー玉

![IMG_0112_copy](https://user-images.githubusercontent.com/1460558/63209086-d3c8c880-c0dc-11e9-9efe-b0be13339290.png)

**Comment by brett-harrison** [comment]
Can also confirm that I cannot input ハート形. Even if I copy the reading from the info page and paste it in to the response box, it still doesn’t work.

I believe this came from the latest update because ビー玉 used to work just fine.

**Comment by ClearOcean9** [comment]
I have same problem.  I cant write ビー玉   Also tried cutting and pasting text from app, but it does not work.  When I do the same in the Wanikani app it works but not with Tsurukame.   I can’t continue if the correct reading is not entered so at a stop

**Comment by joshmcx** [comment]
Same issue with ビー玉
