### ISSUE TITLE
Ending review session causes app to crash on iPad

### ISSUE THREAD

**Issue by lyallcooper** [davidsansome/tsurukame#162]
On my 9.7” iPad running iPadOS 13 Public Beta 6, attempting to end a review session after at least one review has been answered crashes the app. If no items have been answered yet it returns to the main screen as expected.

This crash doesn’t happen on my iPhone X, also running the iOS 13 beta.

**Comment by Rion-Kaneshiro** [comment]
Happened on my iPhone XS Max and iPad Pro (iOS 13 beta 7)

**Comment by StarWitch** [comment]
Confirming that it happens to me as well, on my iPad Mini 4 running iOS 12.4.1.

Does NOT occur on my iPhone XS running iOS 12.4.1. Only on my iPad Mini 4.
