### ISSUE TITLE
Incorrect font used for “part of speech” text

### ISSUE THREAD

**Issue by lyallcooper** [davidsansome/tsurukame#163]
It looks like the part of speech section is using the Hiragino Sans font instead of the usual system font:

![C12D2EB7-BE27-48B3-9F57-907C8632FE44](https://user-images.githubusercontent.com/894902/63234038-45da0400-c1e8-11e9-9dba-d83225c2e0f6.jpeg)

**Comment by davidsansome** [comment]
Thanks!  I fixed this yesterday in 63aaf7af0aa2ef179fbadbcfc793cb31b182d377
