### ISSUE TITLE
Won't accept answer for heart-shaped in new version.

### ISSUE THREAD

**Issue by ad-mico** [davidsansome/tsurukame#168]
I can even cut and paste the answer from what it shows me when I get it wrong, hiragana version or katakana version, won't accept it. Only way out is the end the session without that one. No other way out. Weird, it's the only one that will not accept.

**Comment by davidsansome** [comment]
This is bug #160, caused by the long dash (ー) in ハート形.  I actually fixed it already - you should be able to install an update from the App Store now!

**Comment by ad-mico** [comment]
Thanks!

/A
