### ISSUE TITLE
Delete a synonym

### ISSUE THREAD

**Issue by sujong127** [davidsansome/tsurukame#169]
I’ve somehow entered incorrect synonyms on some kanji and need to know how to delete them! Thank you!

**Comment by bmironer** [comment]
@sujong127 You can open the kanji on www.wanikani.com and delete the synonym there.

But having the option in the app would be nice.
Or at least a confirmation for "Add Synonym". I usually tap it by mistake instead of "Answer was correct" when I have a typo.

**Comment by sujong127** [comment]
@bmironer Thank you! I agree, it think that’d be nice feature! And yes, I’ve also added many an incorrect synonym by mistake.
