### ISSUE TITLE
Incorrect Spelling No Longer Highlights Hiragana on Review Summary

### ISSUE THREAD

**Issue by gilbertyap** [davidsansome/tsurukame#170]
After the latest update, if you get spelling wrong but the definition right, the hiragana isn't bolded in the review summary.

**Comment by turtlemaster19** [comment]
I can confirm this. @davidsansome, this should be straightforward, right?

**Comment by davidsansome** [comment]
Maybe.  It's supposed to be done in https://github.com/davidsansome/tsurukame/blob/master/ios/Tables/TKMSubjectModelItem.m#L143, the bold font is selected in https://github.com/davidsansome/tsurukame/blob/a3040446c42b4e7bd7b9718eb23e19d1bf26c1dc/ios/Style.m#L114.
