### ISSUE TITLE
Emulating Wanikani behavior on wrong answer

### ISSUE THREAD

**Issue by ianklatzco** [davidsansome/tsurukame#172]
When you get a review wrong for a meaning/reading, Wanikani’s webapp only shows you the correct answer for the half you got wrong.

This is good because you don’t see e.g the meaning if you got the reading wrong.

This is an issue with typos — sometimes i might make a typo, mark it as correct, and see the other field before having completed that half of the review. 

Ideally, Tsurukame would only show you the part you got wrong, and let you tap to view the full page.

**Comment by turtlemaster19** [comment]
Related to #49

**Comment by turtlemaster19** [comment]
@indirect or @davidsansome, even the blurring was fine. It might not look great, but it did the job.

I just don't want to see the other half of the answer if it was a typo that Tsurukame didn't catch and I am going to ignore it.

**Comment by tealsummernights** [comment]
When will this be fixed? Every time the app updates on TestFlight I check, but it’s still a problem. The app is unusable for me because of it.

**Comment by UInt2048** [comment]
@tealsummernights #392 should fix it, but I have to fix some merge conflicts first.

**Comment by Takanu** [comment]
Was this in the most recent release?  Im unable to find it 🤔

**Comment by UInt2048** [comment]
@Takanu Hasn't been fixed yet

**Comment by Takanu** [comment]
@UInt2048 No problem, the work done on this app is really appreciated ^_^
