### ISSUE TITLE
Use API to get current data

### ISSUE THREAD

**Issue by UInt2048** [davidsansome/tsurukame#180]
The APIv2 now is able to give the data needed (see AlliCrab for proof) in order to obtain content updates simply via syncing. I don't know much of the technical details, but it should be possible.

> However, for the current mnemonics, being able to update them online, given that minor content updates are pretty frequent, would be useful, so that if a new item were introduced, it wouldn’t crash.

**Comment by davidsansome** [comment]
I think the only thing the API doesn't have is radical mnemonics - we still have to scrape those from the web JSON API.
But yeah apart from that we could potentially fetch new subject content from the API now.  There's a bit of work to canonicalize and clean up the data that's done offline by a Go program - https://github.com/davidsansome/tsurukame/blob/master/cmd/combine/main.go, but we could convert that code to Swift and use it both for generating the offline data file and when fetching new content online.

**Comment by turtlemaster19** [comment]
Just referencing #75 - an example of an issue that was caused by this

**Comment by turtlemaster19** [comment]
@davidsansome, when you look at #238, in case you come here, [the radical mnemonics are exposed](https://community.wanikani.com/t/api-v2-beta-documentation/18987/743?u=japanstar49).

**Comment by davidsansome** [comment]
Thanks!  But it looks like the API is still missing the deprecated_mnemonics for radicals.

**Comment by turtlemaster19** [comment]
They never had or plan to support the deprecated mnemonics, so I suppose we can still use the offline program for that. However, for the new mnemonics, being able to update them online for a content update would be useful, so that if a new item were introduced, it wouldn’t crash.
