### ISSUE TITLE
Add "hints" to reviews

### ISSUE THREAD

**Issue by timmy-lee** [davidsansome/tsurukame#183]
Currently, these are only shown during lessons:
![IMG_3122](https://user-images.githubusercontent.com/20361890/67868515-5280af80-fae9-11e9-816a-5db241f343b8.jpg)

Can we get these to show when looking at the kanji as well as during reviews when we get them wrong?

**Comment by turtlemaster19** [comment]
Great idea. This should be implemented at the same time as #172 - another problem with reviews

**Comment by turtlemaster19** [comment]
@davidsansome Can you add these hints back to lessons as well?

**Comment by davidsansome** [comment]
I don't think I removed them from lessons?

**Comment by turtlemaster19** [comment]
Sorry, I was looking at my vocab lessons, wondering why they weren't there.
Clearly, vocab lessons don't have hints. 🤦‍♂
