### ISSUE TITLE
Upcoming graph lines are now uneven

### ISSUE THREAD

**Issue by indirect** [davidsansome/tsurukame#190]
I've been running `c24e0a285a506897a1bbaac80b345ced006fdd35`, and I noticed that the lines in the "upcoming" graph no longer map to the numbers:

![D12BF280-5505-4649-B355-D5C4C2283E48](https://user-images.githubusercontent.com/78/68080566-ab876680-fdbb-11e9-9a0b-318d326672d9.png)

**Comment by indirect** [comment]
Uh... or... I could build a new copy on a different computer and everything could be back to working! I have no idea. 😬

**Comment by turtlemaster19** [comment]
What? Well, the graph having numbers on the right side is still useful. We should have a TestFlight so that users can test beta features before they're released to the App Store (releasing to the App Store probably won't speed up).

**Comment by turtlemaster19** [comment]
@indirect BTW, where did you get those lines from on the right side? `davidsansome/master` doesn't have those.
