### ISSUE TITLE
Audio no longer works

### ISSUE THREAD

**Issue by indirect** [davidsansome/tsurukame#191]
As of `c24e0a285a506897a1bbaac80b345ced006fdd35`, the audio button is missing from vocab pages, and the "automatically play audio" option doesn't do anything.

![5360C921-72A6-446C-841B-ED8C09C93B4C](https://user-images.githubusercontent.com/78/68080577-dec9f580-fdbb-11e9-9803-e2b7d758ef62.png)

**Comment by indirect** [comment]
Uh... or... I could build a new copy on a different computer and everything could be back to working! I have no idea. 😬

**Comment by turtlemaster19** [comment]
So, #190 and this were solved by re-building it? Definitely weird.
