### ISSUE TITLE
Out of date content(?) - Black listed item in WaniKani is marked as correct in Tsurukame

### ISSUE THREAD

**Issue by andresovela** [davidsansome/tsurukame#193]
Hi,

I recently reported an issue to Wanikani where `intentionally` was accepted as a correct answer for the vocab 思わず (meaning `unintentionally`). I was told by the support team that this item is already blacklisted and that if I use a third-party app, then it might be that the app has outdated content.

I argued that unless the item was added to the black list fairly recently, I doubt that since there were a couple of content updates for Tsurukame not so long ago. I am on version 1.12.

**Comment by turtlemaster19** [comment]
#86 is related to this issue. I agree that this is a problem.
