### ISSUE TITLE
App still not syncing to online account

### ISSUE THREAD

**Issue by udle723** [davidsansome/tsurukame#194]
I'm running version 1.12, which seems to be the newest version of tsurukame, but nothing is registering with my WaniKani account. I'm on level 5 in the app, but only level 2 when I log in on my computer.
Not sure what I'm doing wrong. Any help would be appreciated.

**Comment by turtlemaster19** [comment]
That is the newest build on the App Store. You're saying that the app says you're a higher level than you really are? Can you send a screenshot of what this looks like?

P.S. Can you go to settings and hit export local database and send it in case that's useful to someone?

**Comment by davidsansome** [comment]
This definitely shouldn't be possible.  Can you check you're using the same account on both - that the username at the top of the screen in Tsurukame matches the one on Wanikani?
Otherwise, yep, please export your local database from the app and send it to me@davidsansome.com

**Comment by udle723** [comment]
Oh! I didn't realize I'd made another account. Thanks for taking the time to answer!
