### ISSUE TITLE
Dark mode is unreadable

### ISSUE THREAD

**Issue by bulkan** [davidsansome/tsurukame#198]
Hi there,

Just upgraded to the latest version and dark mode has made the text unreadable.

Disabling dark mode is a temporary work around.

![IMG_2866](https://user-images.githubusercontent.com/13985/68632534-f08d6480-0542-11ea-8d90-ea6eb952be1d.PNG)

**Comment by bengarland** [comment]
Additionally I can no longer read the text in the input box, so I don’t know if it’s asking for Japanese or English.

![B59C10CC-2BC2-4FB2-BE59-624EE417BE72](https://user-images.githubusercontent.com/46571303/68633702-3c85dc80-0536-11ea-8dd6-4ef64e7538ef.png)

**Comment by davidsansome** [comment]
Hmm I didn't intentionally add any support for dark mode this release, I guess it must have happened as a side-effect of building with the iOS 13 SDK.  I'll see if I can fix it.

**Comment by bengarland** [comment]
Also there needs to be a preference in TK to turn Dark Mode off. Just because I have system dark mode on does not necessarily signify that I want to be using TK in dark mode too.

**Comment by bulkan** [comment]
@davidsansome thanks I appreciate all your effort on tsurukame !
