### ISSUE TITLE
Dark mode fixes

### ISSUE THREAD

**Issue by abdulajet** [davidsansome/tsurukame#199]
seems like building in the new xcode has enabled dark mode (sorry if that was me). there are a few areas that need fixing. if folks can drop screenshots in here that would make them easier to find

from settings:
![12E258C2-1C0C-40D5-8FB0-2EF6D87C4952](https://user-images.githubusercontent.com/15106299/68648234-ce322180-0517-11ea-9309-d3659dd994c2.png)
![58901CE9-F571-4599-9BAB-8D1C06BBAD9B](https://user-images.githubusercontent.com/15106299/68648236-ce322180-0517-11ea-9d80-d1b8f8a57495.png

kanji detail screen:
![E589026D-5328-4AA6-BA20-F2D2AAB2D584](https://user-images.githubusercontent.com/15106299/68648345-14878080-0518-11ea-99c7-1994ccd614df.png)

**Comment by davidsansome** [comment]
Note that I've disabled dark mode with fe672b9457e62322a0277ae059e3d21a270b70b1 until we can support it fully.

**Comment by abdulajet** [comment]
awesome, i’ll keep updating this issue with things i find

**Comment by andresovela** [comment]
The chart in the main screen is also broken.
![IMG_0294](https://user-images.githubusercontent.com/8990961/68650435-4d7a2200-0525-11ea-9d02-56e55a998856.PNG)

**Comment by brookshelley** [comment]
I think this is all due to the auto-inversion, vs specifying dark mode colors

**Comment by erujp** [comment]
I have just downloaded the last version from the App Store and I have the same problem (see attachment) because my iPhone is using Dark Mode. If I switch the whole iPhone to Light mode everything in Tsurukame is normal. 
![IMG_5552](https://user-images.githubusercontent.com/15182743/68666818-f3f70f00-0587-11ea-8c79-eadd6779752e.PNG)

**Comment by steakfryday** [comment]
![ECE91470-22FF-4FDB-AED1-FE7F95CDE0F0](https://user-images.githubusercontent.com/44472050/68675214-c7002780-059a-11ea-99bc-2c9a492e02ed.png)
Here’s another shot of Dark Mode. I’m willing to switch back to Light while using this app, but I hope it’s fixed soon.

**Comment by turtlemaster19** [comment]
Would love to see this fixed to fully support #97

**Comment by bulkan** [comment]
This has been fixed in https://github.com/davidsansome/tsurukame/issues/198 and now available on App Store.
