### ISSUE TITLE
Show next upcoming review for current level

### ISSUE THREAD

**Issue by jruberg** [davidsansome/tsurukame#20]
The upcoming reviews display is really nice and slick, but information specifically about current level items (an alternate graph, a display that just says the time that the next current level item will come up, or ideally a local notification when the next current level item is up for review) would be really useful for people trying to level up quickly.

**Comment by jonstrutz11** [comment]
Agreed, this is a feature of the Mobile Allicrab app that I would most like to see in Tsurukame. I especially liked their feature that displayed the theoretical time until level up (assuming all kanji for that level answered correctly) on the home screen - would be great if that could get included here as well.

**Comment by turtlemaster19** [comment]
> I especially liked their feature that displayed the theoretical time until level up (assuming all kanji for that level answered correctly) on the home screen - would be great if that could get included here as well.

That part has been implemented.
As for the original request, good idea!
