### ISSUE TITLE
Animate SRS dots on rank up

### ISSUE THREAD

**Issue by bmironer** [davidsansome/tsurukame#202]
I love the new little dots for SRS ranking! 
But now it kinda feels there's something missing. 
I think I'm expecting them to 'pop' when I get the answer right (or wrong) and the rank changes.
Maybe a simple animation of the dot filling in / out, or just blinking it once or twice...

**Comment by davidsansome** [comment]
@mzsanford what do you think? 😄

**Comment by mzsanford** [comment]
I'll work on adding some transition animations

**Comment by turtlemaster19** [comment]
If we're going to do this, is #10 a thought?
