### ISSUE TITLE
iOS 13 Dark Mode Not Working 

### ISSUE THREAD

**Issue by Kosezu** [davidsansome/tsurukame#203]
Most recent app version 1.14 references iOS 13 Dark Mode issue fixed, but there is no dark mode function on the app. 

Is there in fact a dark mode?

**Comment by davidsansome** [comment]
Duplicate of #198

**Comment by turtlemaster19** [comment]
@Kosezu No, not yet, it wasn't supposed to be added. That's why #97 is still open

**Comment by Kosezu** [comment]
@turtlemaster19 could you please add a dark mode to the app??

I spend a decent amount of time studying at night and it would be a very great help!

**Comment by turtlemaster19** [comment]
I agree, that's why the other issue is still open. It's not exactly easy to add new features, though.
