### ISSUE TITLE
Don't accept nothing as answer

### ISSUE THREAD

**Issue by turtlemaster19** [davidsansome/tsurukame#207]
The checkmark button is able to be clicked without typing anything. It shouldn't be able to do that, like on WaniKani (see [this thread](https://community.wanikani.com/t/what-do-you-type-in-when-you-have-no-idea-what-the-kanji-is/39745))
![IMG_F41AD94CAE15-1](https://user-images.githubusercontent.com/46784000/68908202-32b7d100-0710-11ea-9a3e-d7ca61b24bba.jpeg)

**Comment by davidsansome** [comment]
Oops, I broke this in 237ed095cce0676005f6b75477cca4fedf1003e0 when I converted that class to Swift.  Thanks for noticing it!
