### ISSUE TITLE
Reviews accept empty answers

### ISSUE THREAD

**Issue by andresovela** [davidsansome/tsurukame#210]
The checkmark button is enabled by default when the answer field is still empty. If you type something and delete it afterwards, the button disables correctly.

![IMG_0374](https://user-images.githubusercontent.com/8990961/69224927-abd67e80-0b7d-11ea-9271-4dee765dea24.PNG)

**Comment by davidsansome** [comment]
Thanks for the bug report!  I fixed this already though for #207 - it should be in the next release.

**Comment by andresovela** [comment]
Ah sorry, I did check the issues before posting to avoid duplicating, but it only occurred to me to check the open issues not the closed ones. Thanks!

**Comment by turtlemaster19** [comment]
@davidsansome Can you release a point release (1.14.1) to fix this? This is making me get some Reviews wrong that I actually know the answer to.

**Comment by andresovela** [comment]
Same here

**Comment by davidsansome** [comment]
Yeah it's probably a good idea.  I'll kick off a release now!

**Comment by turtlemaster19** [comment]
@davidsansome I haven't seen it yet, and it's been a whole day. I am not trying to be impatient, but does it take that long to release a bug fix to the App Store?!
