### ISSUE TITLE
item crashing app

### ISSUE THREAD

**Issue by a-papadopoulos** [davidsansome/tsurukame#214]
When I try to view the word 紛れる, the app crashes. I haven't found any other item that crashes the app, so I'm not sure what's the pattern.

**Comment by davidsansome** [comment]
Oops you're right - this look like a crash in the context-sentence-highlighter.  I'll try to fix it!

**Comment by turtlemaster19** [comment]
@davidsansome, this issue has stopped some people from doing Reviews. Can you release this to the App Store?
