### ISSUE TITLE
Refresh does not do anything

### ISSUE THREAD

**Issue by zebala** [davidsansome/tsurukame#217]
Most of the time when I open the app from the suspended state the reviews do not update if I have done some reviews on the PC. Swiping up and getting the "refreshing" has never actually done anything. I have to force close the app and open it again for the review number to update (and even then it is a bit inconsistent). Using iPhone SE with newest iOS.

**Comment by turtlemaster19** [comment]
I agree. Can there be a button for forcing the queued items to update? For example, if there are 130 queued items, it won't upload all of them. It might upload to 84 left, then 50 left. Then, nothing happens, so you close the app - and nothing happens. Then, randomly, you're up to date.

If it's actually trying to update, can you at the very least keep the spinning wheel, or some visual representation that it is in fact syncing?

**Comment by davidsansome** [comment]
Should be fixed by 41e6dacafac811dcbb722cbe17fc6d3d3a07e3a2
