### ISSUE TITLE
楓 broken reading information

### ISSUE THREAD

**Issue by hesch** [davidsansome/tsurukame#220]
The Kanji [楓](https://www.wanikani.com/kanji/楓) has a broken reading explanation in the app.
![700EFD06-90A2-45DB-BF9B-123148B322F0](https://user-images.githubusercontent.com/10466994/69898183-fdd58c00-1355-11ea-978f-871ab9e112cf.png)

**Comment by turtlemaster19** [comment]
Would there be a way to have Tsurukame ignore invalid tags, so we don't keep having these?

**Comment by turtlemaster19** [comment]
But, anyways, can someone fix the overrides list until then?
