### ISSUE TITLE
Feature Request: Automatically switch to Japanese keyboard to input readings

### ISSUE THREAD

**Issue by c-ehrlich** [davidsansome/tsurukame#221]
I don't know if there is an API that does this, but if it's possible, it would be great to have an option that the app switches automatically between the English keyboard (for meanings) and the Japanese keyboard (for readings).

**Comment by turtlemaster19** [comment]
Some people would consider using the Japanese keyboard at all cheating, due to the kanji hints when kana is entered. That would be interesting, though, especially if we could force the kanji hints not to display

**Comment by c-ehrlich** [comment]
True, I hadn't thought about the Kanji auto complete. It should possible to somehow make that not show up - there are some other apps (for example fancy text editors like iA Writer) that modify the default English keyboard in various ways, without having to build their own keyboard from scratch.

**Comment by mzsanford** [comment]
I created a pull request for this so @davidsansome can decide if they want to include the feature or not. I can see it going either way.

**Comment by turtlemaster19** [comment]
It looks like he wants it in. I would like to see it, but I would like to have the feature (if not already):
* optional
* be able to eventually hide the kanji hints (but don't let this stop it from being added)
