### ISSUE TITLE
Funky time remaining estimate

### ISSUE THREAD

**Issue by zebala** [davidsansome/tsurukame#222]
There's still something weird with the level up time, since for this level I actually need 30 kanji done, which is not possible in the amount of time it display. Screenshot below.
![signal-2019-12-01-182530](https://user-images.githubusercontent.com/3922776/69920402-4b561400-1490-11ea-8a21-b672064901a1.png)

**Comment by turtlemaster19** [comment]
I think the level-up time is based on how long it took last level. Was your last level a fast level?

**Comment by zebala** [comment]
Currently 42 so no.
https://github.com/davidsansome/tsurukame/blob/792c64a7f9b0a27803e15362f2abc0e60712742a/ios/LevelTimeRemainingItem.swift#L56

It seems the level up time lowers even if I don't do anything, because it minuses the current time spend on that level.

**Comment by turtlemaster19** [comment]
I see. We should probably check then to make sure that level-up would be possible in that time (so it should be at 6d 20h right now because Radicals are at Lesson)

**Comment by zebala** [comment]
Just an update to see how the time has progressed. Haven't done any lessons since.

![signal-attachment-2019-12-05-114300_001](https://user-images.githubusercontent.com/3922776/70223527-87210000-1754-11ea-908e-71ff7a59132f.png)

**Comment by turtlemaster19** [comment]
Yikes! It went down below 3d 10h. I guess that makes sense since the Radicals haven't been Guru'd, but it shouldn't be doing that
