### ISSUE TITLE
Apprentice count discrepancy

### ISSUE THREAD

**Issue by zebala** [davidsansome/tsurukame#224]
Currently Tsurukame does not count lessons that were just done (and are thus in the 'novice' state) in the apprentice count. Wanikani, however, does. Shouldn't this be changed to mimic the behavior on WK? This would be useful for people who like to keep their apprentice count under a certain limit.

**Comment by turtlemaster19** [comment]
I think we might have #112 for this one.

**Comment by zebala** [comment]
Ah, must have missed that when searching. Personally, I don't really see the point of separating the novice items. I mean they are there usually only for four hours, and information/ui bloat is a thing.

**Comment by turtlemaster19** [comment]
I completely agree. It's definitely a discrepancy with WK and all other resources in existence - I think we should remove it. Let me go edit the other issue.
