### ISSUE TITLE
Lessons not uploaded to wanikani

### ISSUE THREAD

**Issue by hesch** [davidsansome/tsurukame#225]
I just did some Lessons with the app and they don't show up as done in the wanikani webinterface. The lesson counter in turukame is now wrong and the app shows no queued updates.

**Comment by turtlemaster19** [comment]
#184 and #217 are similar, but they haven't mentioned Lessons before. Good luck! Maybe after you Review them, they will sync. 😕

**Comment by turtlemaster19** [comment]
See #277
