### ISSUE TITLE
Error 429 - Too Many Requests

### ISSUE THREAD

**Issue by turtlemaster19** [davidsansome/tsurukame#233]
While trying to generate the data.bin, some of the radicals aren't downloaded because of this error.
![HTTP429](https://user-images.githubusercontent.com/46784000/70366896-d3596680-1860-11ea-8a85-ba6fdbd17f37.png)

Another reason we should consider using the API to get data (#180) and converting Go code to Swift (#189)

**Comment by turtlemaster19** [comment]
Another reason we should consider using the API to get data (#180) and converting Go code to Swift (#189)

**Comment by sciencemanx** [comment]
At the very least some form of exponential backoff + timeout should be used to retry the fetch

**Comment by turtlemaster19** [comment]
One would think that it would try to get all the radicals in one fetch (which is less than 1000 - I believe the limit for fetching) like how it fetches the kanji in groups of 1000.

**Comment by turtlemaster19** [comment]
@davidsansome I thought this wasn't possible anymore since f3c7034 was supposed to fix it:
![Sin título](https://user-images.githubusercontent.com/46784000/71850040-06c62580-3099-11ea-8ea6-07124ee49435.png)

This is using the latest script

**Comment by davidsansome** [comment]
I see the request timestamps are more frequent than 1 per second.  Are you sure you're using the new binary?  How are you running it, with `go run`?  Try running it with the "--request-interval 2s" flag - if that isn't recognised then it's an old binary.

**Comment by turtlemaster19** [comment]
@davidsansome Yes, it's the new binary. The request interval is recognised.
![Sin título](https://user-images.githubusercontent.com/46784000/72228639-29ab7a80-356e-11ea-89ed-3a317f2c927c.png)

**Comment by turtlemaster19** [comment]
The 1.2s request interval does impact this portion:
![Sin título](https://user-images.githubusercontent.com/46784000/72229116-9ffdac00-3571-11ea-8f1c-0662ab6a91b8.png)

**Comment by davidsansome** [comment]
Oops you're right, I'm an idiot, I forgot to apply the rate limit to both types of API client.  Should be fixed by d696fc4bb9793ce43e5621bfbbc3443dafa56815

**Comment by turtlemaster19** [comment]
> I'm an idiot

No, you just forgot something. It happens to all of us! It works correctly now.
