### ISSUE TITLE
Feature Request: Allow user to provide API key

### ISSUE THREAD

**Issue by turtlemaster19** [davidsansome/tsurukame#234]
Currently, the user must provide their account details. The user should be able to instead provide a APIv2 key to their account.

**Comment by davidsansome** [comment]
I actually think making users manage API keys and copy-paste them around between applications is really unfriendly, and I think we'd turn away a lot of users by making them do that.
I wish WaniKani would implement a proper OAuth login flow for third-party applications.

**Comment by turtlemaster19** [comment]
@davidsansome I meant it as an option, not a must, so that if the user would like to change Tsurukame’s permissions or something, they could.
