### ISSUE TITLE
Feature Request: Anonymous Session

### ISSUE THREAD

**Issue by turtlemaster19** [davidsansome/tsurukame#239]
The idea is simple to explain, but probably hard to implement - allow completely offline lessons and reviewing **without** a WK account.

This could be used for a variety of reasons:
- not wanting to create an account
- testing purposes
- [keeping the App Store gods happy](https://github.com/cplaverty/KeitaiWaniKani/issues/45)

The question would be: If we implement it, would we allow the unlocking of Level 4+ items?

**Comment by davidsansome** [comment]
I don't think we'd ever implement this.
All the SRS logic is done by WaniKani so we'd have to reimplement that in the app itself, and I don't really see the purpose...

**Comment by turtlemaster19** [comment]
Well, that makes it simple. Just wanted to mention it!
