### ISSUE TITLE
Update README to address how to install dependencies

### ISSUE THREAD

**Issue by turtlemaster19** [davidsansome/tsurukame#249]
Since the dependencies aren’t included in the app (for good reasons), and come from different sources, the README should explain how to install the dependencies that need to be installed.

**Comment by davidsansome** [comment]
Which dependencies are you referring to?
The third-party iOS libraries are checked in (in the Pods directory), and the Go libraries are pinned by go.mod and fetched the first time you build.

**Comment by turtlemaster19** [comment]
I suppose the Go dependencies take care of themselves.
I was referring to any iOS dependencies that need any instructions to install (CocoaPods isn’t automatically installing all dependencies without any steps)

**Comment by davidsansome** [comment]
The iOS dependencies should be all checked in.  What's the specific problem you're having?

**Comment by turtlemaster19** [comment]
I think the README should explain how `pod install` should be used.

**Comment by turtlemaster19** [comment]
Here are some images that address signing:
<img width="584" alt="General" src="https://user-images.githubusercontent.com/46784000/72098368-ed64e980-32e3-11ea-8cee-e1837d993269.PNG">
<img width="637" alt="Signing & Capabilities" src="https://user-images.githubusercontent.com/46784000/72098370-ed64e980-32e3-11ea-83a9-1783a94213d5.PNG">
