### ISSUE TITLE
Missing Lessons in app

### ISSUE THREAD

**Issue by tauhotdog** [davidsansome/tsurukame#251]
Thanks for all your hard work on the app! Very much appreciated! 

I noticed I haven’t had a lesson in quite a while in the app. I logged into the wanikani site and noticed there were 51 lessons waiting for me but in the app it’s been at 0 for at least 2-3 months.

**Comment by turtlemaster19** [comment]
@tauhotdog We are currently tracking this issue in #94 among others. Can you close it to not crowd out the issues list? Thank you and sorry about that. In the meantime, I would suggest logging out then logging back in to take care of it.
