### ISSUE TITLE
Meaning keyboard always reverts to QWERTY.

### ISSUE THREAD

**Issue by bmironer** [davidsansome/tsurukame#264]
since #36 was released, the keyboard now reverts to English QWERTY on every meaning question, instead of staying on the last selected layout, which is a real pain if you're not used to it.
Note : I'm using the French AZERTY layout, but my OS localization is in English-International.
This happens regardless of the wanikani setting.

**Comment by turtlemaster19** [comment]
Change the auto-select keyboard language setting

**Comment by bmironer** [comment]
This happens regardless of the wanikani auto-select setting.
However, after a bit more testing, it seems it reverts, not to the QWERTY keyboard, but to the 1st one in the Keyboard list.
So just tap Edit in Keyboard Settings... and reordering the French keyboard to the top fixed it.

**Comment by bmironer** [comment]
Mmh not always the 1st one it seems. If Emoji is at the top or adding a bunch of other keyboard with different scripts (Russian, Hebrew...) makes it revert to US english. Might be related to the script language of the answer text field.
Anyway having French AZERTY as the only roman keyboard seems to fix it.

**Comment by turtlemaster19** [comment]
Yes it is related - it's intended to be English. Sorry about that. ;)

**Comment by turtlemaster19** [comment]
@mzsanford Would this be possible to choose the user's default or something? I think you would know more about this than any of the rest of us, since you researched it for #226

**Comment by mzsanford** [comment]
I also run an Arabic keyboard so I'll try some reordering and testing and see if I can fix this.
