### ISSUE TITLE
Genius kanji explanation formatting broken

### ISSUE THREAD

**Issue by Zei33** [davidsansome/tsurukame#268]
Seems that the formatting is broken. Not sure if this is due to a change with WaniKani. I haven't noticed any other issues.

![Example](https://user-images.githubusercontent.com/11221111/72632702-91185e80-39a2-11ea-82ef-7c48b6bce0f6.jpeg)

Also thank you for this incredible app.

**Comment by turtlemaster19** [comment]
Yes. It is - I advise contacting hello@wanikani.com

**Comment by Zei33** [comment]
> @Zei33 Yes. It is - I advise contacting [hello@wanikani.com](mailto:hello@wanikani.com)

Okay I'll let them know. Thanks!
