### ISSUE TITLE
Breakdown the review count by SRS level

### ISSUE THREAD

**Issue by bmironer** [davidsansome/tsurukame#274]
Since level ~40 I’m having trouble keeping up with reviews. So I try to at least do my Apprentice and Guru reviews, and pick at the higher levels when I can. Sorting reviews by SRS level is perfect for that. We have a total tally of the cards by SRS level and now ‘next level up review’ gives me a idea of when I have Apprentice lessons coming up.

But I have no idea of how many Guru, Master or Enlightened review I have queued up and if it’s getting better or worse. 

The details could be added to the All level list such as :

ALL LEVELS          REVIEWS / TOTALS
Apprentice             123 / 136
Guru                       834 / 1071
Master                   324 / 477
Enlightened          1217 / 1796
Burned                       - / 3085

**Comment by davidsansome** [comment]
This could be quite similar to #260.
I'd like to have the "upcoming reviews" chart indicate the SRS stage of the reviews that make up each bar.  It might be intuitive to show the breakdown of currently available reviews next to that.

**Comment by turtlemaster19** [comment]
This may help finally finish #112

**Comment by bmironer** [comment]
Yes, it seems the same a .2 in #112. 
#260 is different but has a similar purpose I guess.

**Comment by turtlemaster19** [comment]
@bmironer #261 was closed due to this very request, so that's why David Sansome mentioned it.
