### ISSUE TITLE
Kanji order from lessons different from website

### ISSUE THREAD

**Issue by dambros** [davidsansome/tsurukame#279]
This may be irrelevant most of the time, but I've just started using Wanikani (so still level 1) and one of the first kanji they teach about is エ and on the same batch of kanjis, they will then teach 人.  
The thing is, they build the mnemonics for 人 using the mnemonics you learned on エ, so in this very particular case the order the kanjis are displayed on a lesson matters. 

While using the app to do this particular lesson, I had a batch of five kanjis and it showed the kanji 人 right away without even listing エ on that lesson, which made no sense. I then decided to check the website because it looked like an error on their end, but on the website the same lesson (clicked Start Session) showed エ first and then 人.

I don't know if the app randoms the kanjis to display in a lesson when there are more than the number of kanjis set to be displayed in a lesson, but if it does I think maintaining the original order should be priority to avoid situations like this.

**Comment by turtlemaster19** [comment]
@dambros It is randomized, which actually matches WK behavior, believe it or not. WK will randomize them, too. There isn’t really an “original order” to begin with. We are hoping to add more sorting options, though.

**Comment by turtlemaster19** [comment]
@dambros If you go to https://www.wanikani.com/level/1 you will see it ordered in alphabetical English order. Is that the “order” you want your lessons in? No randomizing, just straight from that page?

**Comment by dambros** [comment]
@turtlemaster19 I was revising my original post and I incorrectly referenced the kanji mnemonics relationship. It is actually 口 - 工 and not 人 - 工, my bad.

As you can see, both have the same reading and on 口 they use the character they introduced previously on 工 ("Remember seeing the construction worker こういち earlier in the 工 mnemonic?").

> @dambros If you go to https://www.wanikani.com/level/1 you will see it ordered in alphabetical English order. Is that the “order” you want your lessons in? No randomizing, just straight from that page?

This order is appropriate because 工 comes first.

**Comment by turtlemaster19** [comment]
@dambros I realized that this mnemonic issue is more of a WK-side thing, so I filed a request here: https://community.wanikani.com/t/level-1-%E5%8F%A3-mnemonic/41678
I encourage you to comment there!

**Comment by dambros** [comment]
Thanks and done. I believe this issue can be closed.

**Comment by turtlemaster19** [comment]
@dambros The mnemonic has been updated on the site now. Thank you for reporting this!
