### ISSUE TITLE
macOS: crash at startup once logged in

### ISSUE THREAD

**Issue by bmironer** [davidsansome/tsurukame#283]
the `headerView` is sometimes nil in `refresh()` and `updateUserInfo()` at startup with login info in the settings.
`guard let headerView = headerView else { return }` in both functions is enough to workaround.

**Comment by zapan** [comment]
Thanks! Works like a charm 😀

**Comment by turtlemaster19** [comment]
https://github.com/davidsansome/tsurukame/blob/5d25135fcbdc7f9e37d2dda49b6ef15f6eacda26/ios/MainViewController.swift#L365

https://github.com/davidsansome/tsurukame/blob/5d25135fcbdc7f9e37d2dda49b6ef15f6eacda26/ios/MainViewController.swift#L385-L387
