### ISSUE TITLE
macOS : various issues

### ISSUE THREAD

**Issue by bmironer** [davidsansome/tsurukame#286]
Quick grab-bag of issues in the (home-built) macOS version. 

- all TableViews in the macOS version use grey cell background with white (or black) section header backgrounds. This is the reverse than on iOS and since text still has its white (or black) background, it shows (in settings, kanji info, lessons etc..)

- The labels and text feel small on a 15" macbook screen. 
Maybe globally bump it by 150 or 200% ?
Same for the squarish kanji icons and little page markers in lessons. 
(the 'previous kanji' button in reviews is bigger and feels the right size)

- the dashboard header is missing a bit of inset space at the top.

- the dashboard piecharts do not live-relayout like the rest of the dashboard when dragging the window. They do relayout properly to the new size when coming back from another view.

- macOS build can't verify 3rd party libs (requires disabling library verification to launch)

- no way to dismiss the review ending summary with the keyboard. Is there a standard keyboard equivalent to the 'Done' button? (forgot to try Esc. Return seems obvious but didn't work)

- Pressing 'Down Arrow' on the home screen with no review queued goes to an empty black screen with no way back except quitting. (With reviews queued it goes to reviews)

### Fixed

- in the Audio download screen  'Download audio to your *phone*..." should probably say '... to your device' instead. (fixed by #287)

- badging the icon doesn't work. see #19 (fixed)

- macOS build tries and fails to package the complication module, which is not supported on macOS (fixed)

- the particle 'pop' animation has to finish before the keyboard is active.
Using back-to-back reviews I can start typing the reading right after I press return on the meaning. I then lose the first keystrokes while the animation plays.
Couldn't reproduce on iOS with the on screen keyboard. Maybe the keys are buffered? Didn't try with a bluetooth keyboard either (fixed by #381)

- Answer field loses keyboard focus after 'shake' animation (after a correct kanji answer to a vocabulary question or after a typo on hiragana). (fixed by #381)

**Comment by UInt2048** [comment]
@bmironer Can you add #381 to your fixed list?

**Comment by bmironer** [comment]
> @bmironer Can you add #381 to your fixed list?

sure, I will check the fix later when I get a few more reviews. 

maybe related:  I just found that pressing 'down arrow' on the home screen of the mac version opens an empty black scene with no way back ( commit cfa3dc5aa0c7c0e91a15deb020ba350666ff7eae )

**Comment by UInt2048** [comment]
> macOS build can't verify 3rd party libs (requires disabling library verification to launch)

Possibly fixed on latest macOS/Xcode. Seems like an issue quite similar to one I previously experienced with iOS 13.3.1.

**Comment by bmironer** [comment]
> > macOS build can't verify 3rd party libs (requires disabling library verification to launch)
> 
> Possibly fixed on latest macOS/Xcode. Seems like an issue quite similar to one I previously experienced with iOS 13.3.1.

Still get an error on Charts
```
dyld: Library not loaded: @rpath/Charts.framework/Versions/A/Charts
  Referenced from: /Users/bmironer/Library/Developer/Xcode/DerivedData/Tsurukame-azjcesfjswsypjbpxjuhlypsogpv/Build/Products/Debug-maccatalyst/Tsurukame.app/Contents/MacOS/Tsurukame
  Reason: no suitable image found.  Did find:
	/Users/bmironer/Library/Developer/Xcode/DerivedData/Tsurukame-azjcesfjswsypjbpxjuhlypsogpv/Build/Products/Debug-maccatalyst/Tsurukame.app/Contents/MacOS/../Frameworks/Charts.framework/Charts: code signature in (/Users/bmironer/Library/Developer/Xcode/DerivedData/Tsurukame-azjcesfjswsypjbpxjuhlypsogpv/Build/Products/Debug-maccatalyst/Tsurukame.app/Contents/MacOS/../Frameworks/Charts.framework/Charts) not valid for use in process using Library Validation: mapped file has no Team ID and is not a platform binary (signed with custom identity or adhoc?)
	/Users/bmironer/Library/Developer/Xcode/DerivedData/Tsurukame-azjcesfjswsypjbpxjuhlypsogpv/Build/Products/Debug-maccatalyst/Tsurukame.app/Contents/MacOS/../Frameworks/Charts.framework/Versions/A/Charts: code signature in (/Users/bmironer/Library/Developer/Xcode/DerivedData/Tsurukame-azjcesfjswsypjbpxjuhlypsogpv/Build/Products/Debug-maccatalyst/Tsurukame.app/Contents/MacOS/../Frameworks/Charts.framework/Versions/A/Charts) not valid for use in process using Library Validation: mapped file has no Team ID and is not a platform binary (signed with custom identity or adhoc?)
```

**Comment by bmironer** [comment]
> > @bmironer Can you add #381 to your fixed list?
> 
> sure, I will check the fix later when I get a few more reviews.
> 
> maybe related: I just found that pressing 'down arrow' on the home screen of the mac version opens an empty black scene with no way back ( commit [cfa3dc5](https://github.com/davidsansome/tsurukame/commit/cfa3dc5aa0c7c0e91a15deb020ba350666ff7eae) )

Ok I figured it out. It's down arrow on the home *with no review queued* 
With reviews available, it goes to the reviews.

**Comment by bmironer** [comment]
> @bmironer Can you add #381 to your fixed list?

Could not reproduce. Marking fixed.

**Comment by bmironer** [comment]
The remaining issues all seem fixed in catalyst on mac. So I'll close this very old report and open a new one for the new issues.
