### ISSUE TITLE
Unlocks lessons before the website

### ISSUE THREAD

**Issue by patrickkelso** [davidsansome/tsurukame#29]
iPad Air 2 running IOS 11.3
Tsurukame shows I have 101 lessons ready. Wanikani.com shows I have 0. And Tsurukame will let me do the lessons.

I noticed this the other day when I was offline I kept having new lessons for Kanji beyond what I thought I should have. I had just levelled up. and Tsurukame had let me learn all the new Kanji for my level instead of only the Kanji that used my Guru'd radicals.

I thought it might have been an anomaly however I'm online now and it's still showing me 116 vocab lessons that I have definitely not unlocked.

(I would like to request that functionality stays but as an option. I restarted from level 3 after an 18 month break when I just couldn't face the 2000+ reviews that I couldn't remember up to level 23. Now that I'm starting lower with a smaller number of reviews I'm powering through it because I don't need the full SRS timing so for me this is a feature).

**Comment by patrickkelso** [comment]
It's possible this is a WK issue. I just noticed that WK tells me I unlocked 食 in September 2016. Which I did, but then I reset to below level 6 which 食 is in. So it should show my unlock day as 28/4/2018 which is when I re-unlocked it.

**Comment by davidsansome** [comment]
I think this is due to the reset - Tsurukame is probably looking at the original date you unlocked everything, and concluding that since it's in the past everything is available now.

**Comment by davidsansome** [comment]
Oh actually it looks like the API has changed in the last week or so - it's now returning *all* assignments, even the ones that aren't unlocked yet.  Maybe afe1eaf3236f3e47f04c012e6e03188cc93f4a54 will fix it.
