### ISSUE TITLE
Reviews keep repeating the same 3 items

### ISSUE THREAD

**Issue by evertonminami** [davidsansome/tsurukame#292]
Hi,

For the past 3 weeks, I've been having this issue where the same 3 items keep coming back in my reviews, so every time there is a new these 3 items are always there.

There are 1 kanji and 2 words:
kanji: 久
vocabulary: 久しい
vocabulary: 久しぶり

I've attached the latest copy of my local-cache-db if it helps.
I've tried logging out and in, but the issue remains.

Any idea why this is happening?
Thanks

[local-cache.db.zip](https://github.com/davidsansome/tsurukame/files/4168981/local-cache.db.zip)

**Comment by EmmaINSA** [comment]
The same thing happens to me with 久しい when I manually refresh the app on the main screen. I haven't tried anything like uninstalling or logging out though.

**Comment by turtlemaster19** [comment]
Solved by #269

**Comment by turtlemaster19** [comment]
@davidsansome It would be great if we could release to the App Store, so people don't keep being affected by this issue.
