### ISSUE TITLE
Feature Request: Heisig Cross-Reference Numbers

### ISSUE THREAD

**Issue by turtlemaster19** [davidsansome/tsurukame#303]
Please read @mzsanford's reply

**Comment by mzsanford** [comment]
This feels more like a dictionary feature than a lesson/review feature. It might be better served by installing a dictionary app in addition to Tsurukame (I use [Shirabe Jisho](https://apps.apple.com/us/app/shirabe-jisho/id1005203380) but there are others).

If we want to add more dictionary style features like this and #253 then the [KANJIDIC Project](https://www.edrdg.org/wiki/index.php/KANJIDIC_Project) has all of the various dictionary indices.

**Comment by turtlemaster19** [comment]
@mzsanford Agree. Would you mind mentioning this on the forum to the user who actually requested this? I am just putting people's suggestions as proper GitHub requests.

**Comment by mzsanford** [comment]
Replied to forum request: https://community.wanikani.com/t/ios-tsurukame-native-app-with-offline-lessons-and-reviews/30635/592

**Comment by turtlemaster19** [comment]
@mzsanford I will close **this** issue. If someone else feels differently that this should be a part of Tsurukame, please let me know why and/or implement it. 😜
