### ISSUE TITLE
Some reviews are stuck and do not go away

### ISSUE THREAD

**Issue by eriklebel** [davidsansome/tsurukame#305]
I have six reviews that never go away.

From what I can tell, there should be master or enlightened, but as soon as I review (successfully) they stay in the review stack. 

On the wanikani web interface these are not scheduled for a long time still. 

I am stuck re-reviewing these six in every review. 

What I can see is that wanikani re-ordered there’s kanji to a future level I have not started yet. I believe that the problem is tried  to incorrectly interpreting these as needing reviewing.

**Comment by turtlemaster19** [comment]
@eriklebel 
> Duplicate of #83 - solved by #269
> The problem is that these items are actually **above** your current level, so WK refuses to accept the reviews.
> Use the TestFlight build link from the README.
> 
> @davidsansome It would be great if we could release to the App Store, so people don't keep being affected by this issue.

**Comment by turtlemaster19** [comment]
Just wanted to add that this was closed as a duplicate of several other resolved issues such as #83 and #324, to name a few.
