### ISSUE TITLE
Incorrect vocab lesson for “genius”

### ISSUE THREAD

**Issue by dinosachi** [davidsansome/tsurukame#309]
In this image, the vocab for “genius” appears to be parsed incorrectly. 

![27A42575-124E-461D-95D3-3E2C62288CCD](https://user-images.githubusercontent.com/57275561/75705742-dbaf1b00-5c70-11ea-8bcf-31136177021c.png)

**Comment by turtlemaster19** [comment]
Thanks. I shot WK support a forum thread: https://community.wanikani.com/t/才-tag-error/42284

**Comment by turtlemaster19** [comment]
@dinosachi The issue has been corrected with WK and will be immediately fixed in the next TestFlight update and/or App Store release. Unfortunately, auto-updating the DB isn't yet possible. 😿
