### ISSUE TITLE
While offline, completed lessons aren't added to the review queue

### ISSUE THREAD

**Issue by jeff8v7** [davidsansome/tsurukame#312]
Yesterday, flying from LA to Tokyo, I refreshed my app before takeoff. While flying (offline), I caught up my pending lessons. I was anticipating that these newly completed lesson items (169 radicals, kanji, and vocab) would be available as reviews up a few hours later, but I didn't see them in the review graph.  Even after taking my review count from 184 to 0, the items from my recent offline lessons were not in the review queue.

Out of curiosity, I purchased an hour of wifi on the plane, let the app sync, then watched the wanikani website slowly update my lesson and review counts. As expected, it all sorted itself out with a little patience and connectivity.

Seems like it would be helpful if this case if the app queued up completed lessons automatically, even if it can't contact the wanikani server :-)

**Comment by turtlemaster19** [comment]
@jeff8v7 Agree. This is actually addressed in other issues such as #87. Consider giving that a quick read.

**Comment by jeff8v7** [comment]
@turtlemaster19  Thanks - looks like #87 is closed.  Perhaps can leave this open as a feature request.

**Comment by turtlemaster19** [comment]
@jeff8v7 It was actually closed as a duplicate of another issue, namely #94 and #184, since they are all one problem, as confirmed in their discussions. Would you mind closing this to cut down on dupes?

**Comment by jeff8v7** [comment]
> Would you mind closing this to cut down on dupes?

sure
