### ISSUE TITLE
Long words get cutoff (with ellipsis) during review

### ISSUE THREAD

**Issue by jeff8v7** [davidsansome/tsurukame#313]
On iOS (iPhone X), review words longer than 3 letters get cut off with an ellipsis, which makes for a fun guessing game.

Update: Still seeing the ellipsis for 4 character words if font size is 250% (on iPhone X, Tsurukame Version 1.20 (693).  But any other font size is fine (225% is fine).   I sent a screenshot from testflight.

Seems unlikely anyone will every need 250% font size, but still....

 
![E8ACDF0F-7E9B-447E-92E6-D4E4D61A9C91](https://user-images.githubusercontent.com/39231776/75976453-cd395b80-5f1d-11ea-9bf0-6da8ddc0d078.jpeg)

**Comment by turtlemaster19** [comment]
@jeff8v7 It might help if you decrease the font size for now, 250% seems a bit ridiculous for an iPhone X.

**Comment by jeff8v7** [comment]
Actually, this was with font size 100%, because the font size wasn't working when I took this screen shot.  Today's update 1.18 (681) changed the behavior, so that font size does make this bigger (but strangely doesn't affect any other fonts in the app)

**Comment by turtlemaster19** [comment]
@jeff8v7 That's intended behavior. Any other behavior should receive its own feature request.

**Comment by turtlemaster19** [comment]
@jeff8v7 Are you still having this problem?

**Comment by jeff8v7** [comment]
Not sure. I don’t usually review in iPhone, but I’ll try some and see if I can get this issue again.

**Comment by jeff8v7** [comment]
Still seeing the ellipsis for 4 character words if font size is 250% (on iPhone X, Tsurukame Version 1.20 (693).  But any other font size is fine (225% is fine).   I sent a screenshot from testflight.

Seems unlikely anyone will every need 250% font size, but still....

**Comment by turtlemaster19** [comment]
@jeff8v7 Would you mind updating the first post of the issue with this?

**Comment by turtlemaster19** [comment]
@jeff8v7 It is an important issue, especially for `お誕生日おめでとう` which fills the entire screen at 100%.
