### ISSUE TITLE
macos : Answer fields loses keyboard focus after 'shake' animation 

### ISSUE THREAD

**Issue by bmironer** [davidsansome/tsurukame#319]

**Comment by turtlemaster19** [comment]
Dupe of #286 

> the particle animation has to finish before the keyboard is active.
Using back-to-back reviews I can start typing the reading right after I press return on the meaning. I then lose the first keystrokes while the animation plays.
Couldn't reproduce on iOS with the on screen keyboard. Maybe the keys are buffered? Didn't try with a bluetooth keyboard either

**Comment by bmironer** [comment]
Might be related but it's different I think. 

After the shake animation (the one when you gave the kanji reading to the vocabulary question), the focus never goes back to the field unless you click it. 

Whereas #286 is about the 'pop' animation (after a correct level up answer) delaying the focus, which does come back on its own, but after the animation is done. 

Both could be solved at the same time I guess. I'll amend #286.
