### ISSUE TITLE
Option to increase number of lessons per batch in app

### ISSUE THREAD

**Issue by mztik** [davidsansome/tsurukame#32]
The default in WaniKani is 5 lessons per batch, which seems to be the case for Tsurukame as well. However, I have this option set to 10 lessons per batch in WaniKani, and Tsurukame is still giving me 5 lessons per batch. I'm guessing you don't import user settings from WaniKani, which leads me to ask for the addition of an option to increase the number of lessons per batch. Thanks!

**Comment by davidsansome** [comment]
Fixed by commit d5cb50ec46a43ed0113114f0c951b724ac9bca36!
