### ISSUE TITLE
API error, not loading in iOS 13.3.1

### ISSUE THREAD

**Issue by wrldpc** [davidsansome/tsurukame#320]
Login at the home screen, app cycles, throws error:

“Error occurred fetching API key”

![0CB5F315-CA13-4087-A721-B6E97D3CC761](https://user-images.githubusercontent.com/108031/77218724-c80d1b00-6b71-11ea-9538-7c98d1b3285c.png)

**Comment by davidsansome** [comment]
I'm unable to reproduce the problem - it works for me!
Can you try going to https://www.wanikani.com/settings/personal_access_tokens and see if you have a "Tsurukame" API token already?  If so try deleting it, then log in using the app again.
