### ISSUE TITLE
Radical does not progress

### ISSUE THREAD

**Issue by Rion-Kaneshiro** [davidsansome/tsurukame#324]
I have a radical since yesterday that seems to be stuck on guru one and reappears in reviews all the time although it’s already answered correct.
When I reload after I finished the reviews it appears as a review again.

On the Wanikani website I do not have any open reviews, just in the app.
I deleted and reinstalled the app an there it was again.

**Comment by turtlemaster19** [comment]
@Rion-Kaneshiro Good news! We just released an update to fix this! Please update the app.

**Comment by davidsansome** [comment]
Apple took much longer than usual to approve this new release, it only just went out to the App Store a few hours ago!

**Comment by Rion-Kaneshiro** [comment]
Updated and I can confirm
It’s still happening :/

**Comment by turtlemaster19** [comment]
@Rion-Kaneshiro Really? You're on 1.18 now?

Anyways, it may be useful to now which one it is.

**Comment by Rion-Kaneshiro** [comment]
Yes, latest version from the store.

Would it help you to export the database?

**Comment by turtlemaster19** [comment]
@Rion-Kaneshiro I would be more interested at the moment to know which radical it is.

**Comment by Rion-Kaneshiro** [comment]
https://www.wanikani.com/radicals/hills

**Comment by turtlemaster19** [comment]
@Rion-Kaneshiro Thank God they moved it! I was a part of the thread asking for it to be moved.

In that case, it will be corrected in the next App Store release, which will be out as soon as Apple approves it.

**Comment by Rion-Kaneshiro** [comment]
Cool, thanks :)

**Comment by davidsansome** [comment]
Oops sorry I was mistaken - it looks like Wanikani updated this radical **after** I created the database for 1.18 and 1.19, so the update won't fix the issue.
I'll have to release another update with the new data.

**Comment by turtlemaster19** [comment]
Yep, the official content update thread for it is here:

https://community.wanikani.com/t/march-27-2020-content-updates/42798

**Comment by jeff8v7** [comment]
Same problem. Hills radical is stuck in my review queue. Is there a way to reset a radical's progress to 0 in wanikani? Otherwise, I'm going to know it really really well :-)

**Comment by turtlemaster19** [comment]
@jeff8v7 If it has been burned in WaniKani, it can be resurrected.

Otherwise, I am afraid not. As soon as the next TestFlight build or App Store release comes, neither of which have occurred yet, this issue will go away.

**Comment by turtlemaster19** [comment]
@davidsansome Now the TestFlight build has been approved, you should be able to close this.

https://community.wanikani.com/t/ios-tsurukame-native-app-with-offline-lessons-and-reviews/30635/612
