### ISSUE TITLE
TestFlight Error

### ISSUE THREAD

**Issue by turtlemaster19** [davidsansome/tsurukame#327]
Recent attempted TestFlight building failing due to:

> The request could not be completed because:
	Invalid username and password combination. Used 'me2@davidsansome.com' as the username.

**Comment by davidsansome** [comment]
I manged to get the old circleci@davidsansome.com apple ID into a weird state, so I created a new circleci2@davidsansome.com which seems to work!

**Comment by turtlemaster19** [comment]
@davidsansome Strangely, the TestFlight test passed, but I can't see the build in TestFlight. What's up with that?

**Comment by turtlemaster19** [comment]
@davidsansome Can you please explain this?

**Comment by davidsansome** [comment]
Looks like it's waiting for Apple review:
![image](https://user-images.githubusercontent.com/314463/77867207-0b5a3e80-7282-11ea-93e6-cb1aa5632c55.png)

Builds usually get approved automatically if there's only a small change from the previous version, but I guess adding the WatchKit extension was a sufficiently large change that it's gone back to manual review again.  Maybe after a couple of these are approved manually it'll go back to automatic?

**Comment by turtlemaster19** [comment]
Come on, seriously?!?
Just frustrated — I didn't think that was possible.

Upon research, it seems to happen every time the **version** increases, but not when the build does.

**Comment by turtlemaster19** [comment]
@davidsansome After bumping to 1.21, the TestFlight process is failing with:

> Missing required information to submit for external testing - Missing requied [sic] data.

Please fix this if anything needs to be adjusted.
