### ISSUE TITLE
Can’t Tap Review Batch Size

### ISSUE THREAD

**Issue by SomeGuyNamedDavid** [davidsansome/tsurukame#328]
I’m unable to click on the newly-added “Review Batch Size” option in the settings, leaving it stuck at 5. Additionally, the actual process of doing my reviews seems unchanged.

**Comment by turtlemaster19** [comment]
For anyone reading this issue in the future, see the discussion at the referenced issue...

**Comment by SomeGuyNamedDavid** [comment]
As of update 1.20, the review batch size selector now works, allowing a Wrap-Up size ranging from 3 to 10.
