### ISSUE TITLE
Feature Request: Wrap-Up Size Setting

### ISSUE THREAD

**Issue by SomeGuyNamedDavid** [davidsansome/tsurukame#329]
From observations, I assume the app tries to limit you to a maximum of 5 half-completed reviews at a time, so that Wrap-Up can finish all those reviews in order to not discard any progress.

I like there to be a larger average time between being tested on a meaning and its corresponding meaning, so the ability to increase the Wrap-Up length would be nice.

**Comment by davidsansome** [comment]
You should be able to change this with the Review Batch Size setting, although as you noticed in #328 it doesn't work :(
It should be tappable in the next release!

**Comment by SomeGuyNamedDavid** [comment]
Noted, thank you!

**Comment by turtlemaster19** [comment]
@SomeGuyNamedDavid No, thank you! I actually implemented this, but didn't heed the warning that the method that actually allowed you to tap on it (like 3 lines of code) was missing.🤦🏻‍♂️

I'm glad this feature will be useful!
