### ISSUE TITLE
English translations blurred out in vocabulary items. 

### ISSUE THREAD

**Issue by Croalface** [davidsansome/tsurukame#333]
Hi. I love Tsurukame, thanks so much for creating it. I’ve just seen that the English translations of the sample sentences showing vocabulary items are all blurred out. How can I rectify this? Pic uploaded to show the problem. 

Thanks,

Paul Kaye
London 

![145551A6-CE2A-4F5E-BD17-3F6186E877DE](https://user-images.githubusercontent.com/62848513/77855345-bd90f800-71e7-11ea-9e1a-62b0508df76c.png)

**Comment by zapan** [comment]
Tap on the blurred text to show translation ;)

**Comment by turtlemaster19** [comment]
Yep, that's an intentional feature. I don't want it removed — it makes it more interesting, since your eyes can't be drawn to the English if it's hidden, so you have to look at the Japanese.

**Comment by Croalface** [comment]
Hello,

That’s fine, I’m sure it will be useful, but I just didn’t know the change was happening and didn’t realise I could reveal the English by tapping. My first assumption was that WaniKani were limiting your access to that information and so it wouldn’t display. For future reference, how is information on big changes to the app like this circulated?

Thanks again,

Paul

Sent from my phone

**Comment by Croalface** [comment]
Thanks for the tip!

Sent from my phone

**Comment by davidsansome** [comment]
At the moment these changes are only in the "What's New" section on the App Store: https://apps.apple.com/au/app/tsurukame-for-wanikani/id1367114761, which admittedly is not much use to you if your apps auto-update.

I wanted to add an in-app "What's New" popup when you update to a new version, but I didn't get around to it yet.  I've created #336 to track that.
