### ISSUE TITLE
Unusual Activity Progress Indicator Behaviour

### ISSUE THREAD

**Issue by bloomingbridges** [davidsansome/tsurukame#339]
Hi Davidさん，

I might be imagining this, but ever since the WK API v.2.0 was officially released last week, the sync progress bar is behaving oddly, in that it either 

A) is super slow (which may well be a side effect of quarantine internet throttling)
and or
B) goes up to 100% twice.

The data is still being synched as far as I can tell, so not really an issue, just something I wanted to let you know, so feel free to close.

Cheers,
Florian from Germany

**Comment by turtlemaster19** [comment]
More information might be useful to fixing it, such as screen recordings, dev logs, etc. I don't seem to experience this.

Do note that it's slow because it is refreshing every item on WaniKani. :P

**Comment by bloomingbridges** [comment]
Hi @turtlemaster19 ,
Indeed, I haven't noticed it recently either.. 🤷‍♂️ 
Tried taking several screen recordings throughout my daily sessions and everything seems back to normal. Sorry about the false alarm.
