### ISSUE TITLE
Feature Request: Stroke order diagrams from Jisho, possible?

### ISSUE THREAD

**Issue by AzzyLuddy** [davidsansome/tsurukame#344]
There is a certain script for the WaniKani website that pulls stroke order diagrams from Jisho to display them to you during lessons and whenever you get an answer wrong during reviews, would this be a possible feature for Tsurukame? Might be niche, but I’m an iPad Pro user who uses Tsurukame alongside Good notes in split screen to write lessons and rewrite reviews, would be awesome to have this feature!

**Comment by AzzyLuddy** [comment]
Closing, duplicate. My apologies!

**Comment by turtlemaster19** [comment]
@AzzyLuddy No problem. Just wanted to let you know that if you make a **reading** note on the WK website, it will show in Tsurukame. Just a fun little Easter egg you might enjoy!
