### ISSUE TITLE
Feature Request: Show sub-SRS level counts on dashboard

### ISSUE THREAD

**Issue by Mercieral** [davidsansome/tsurukame#345]
I would really like some way to see the individual sub-SRS level counts (IE: apprentice 1-4 and guru 1-2).

Essentially what these user scripts are showing on the web dashboard.
https://community.wanikani.com/t/userscript-yet-another-wk-dashboard-individual-srs-totals/37373
https://community.wanikani.com/t/userscript-wanikani-dashboard-srs-and-leech-breakdown/32756

Some potential options I'm thinking of...

- Making the apprentice and guru list items at the bottom of the dashboard clickable (with some form of UI to indicate that they are clickable of course) and expand to show sub-srs level counts.
- Showing the sub counts inline on the apprentice and guru list items. (keep in mind narrow phones...)
- Setting to change the count between total vs sub-level counts.

**Comment by turtlemaster19** [comment]
@Mercieral Dupe of #112

**Comment by turtlemaster19** [comment]
@Mercieral Please close this and comment in #112 instead. This is a duplicate issue.

**Comment by Mercieral** [comment]
Ok, but my concern is that issue is not easily tracked and will be missed because the title is incredibly vague with just "A bit more info". Hence why I didn't even know the feature was already requested...
