### ISSUE TITLE
Feature Request: Anki mode

### ISSUE THREAD

**Issue by oguzgelal** [davidsansome/tsurukame#347]
A special mode that works like Anki. Tapping on the screen reveals the answer (reading or meaning depending on the question but not both - to avoid spoiling the following questions). On the answer screen there would also be "Correct" / "Incorrect" buttons that marks the answer (or even maybe Tinder-style swipe left / right). 

This would basically be equivalent of submitting an incorrect answer, then hitting "My Answer Was Correct", but without the reveal of the full answer card and with an optimized UI intended for this interaction. This would definitely speed up reviews as it is a burden to type the answers every time.

**Comment by turtlemaster19** [comment]
Wow, that looks like two requests in one, but I'm not surprised it finally came up! ;)

To do this, #172 would be mandatory.

After that, #48 would probably happen, since it seems to be a similar idea - an incorrect button on the left and a correct button on the right.

**Comment by oguzgelal** [comment]
> Wow, that looks like two requests in one

Haha seems like it, sorry about that 😅

> if you are going to mark it wrong you might want to see the explanation and hint below.

Right, I'm assuming after https://github.com/davidsansome/tsurukame/issues/49 is implemented and the ability to separate those fields is there, the rest would be easy. On "Anki Mode" all it'd take would be to just fire up the subject details view (like when you get the answer wrong) with parts other than the answer hidden, and render two buttons, "Correct" button wired up to "My answer was correct" and "Wrong" button wired up to that right arrow next to your wrong answer that you click while hating yourself.

**Comment by turtlemaster19** [comment]
@oguzgelal Looks right! Glad that somebody thought to request it, and I'm wondering why it hasn't been requested sooner with its depending requests being so old
