### ISSUE TITLE
Feature Request: Keyboard shortcut for “Ask again later”

### ISSUE THREAD

**Issue by rubyroobs** [davidsansome/tsurukame#349]
Tsurukame is really fun with the new iPad Pro Magic Keyboard, but it’s a bit of a flow-killer to have to stop and move the mouse/touch the plus to then process “ask again later” if I make a typo. It would be really useful if the app could support the escape key to bind to “Ask again later” for keyboard users who use the similar extension for PC!

I may actually take a pop at this if I get some free time ☺️

**Comment by turtlemaster19** [comment]
Doesn't this already exist at:

https://github.com/davidsansome/tsurukame/blob/1f7d3b80ef24fdd716435784bdfc9fedd6608166/ios/ReviewViewController.swift#L1239-L1242

**Comment by rubyroobs** [comment]
Seems it does! Thank you @turtlemaster19 !!!
