### ISSUE TITLE
Keyboard resizing

### ISSUE THREAD

**Issue by kevananderson** [davidsansome/tsurukame#35]
On iPhone 8. I use Japanese native iOS 11 keyboard. Also I use Swype keyboard for English. The problem is when I switch to do my lesson after reviewing. If i have left my Japanese keyboard as my last keyboard, when I start typing, the keyboard grows to suggest kanji and the app does not resize. The keyboard covers the input box. My workaround is to exit the learning or review, switch to Swype keyboard then start lesson again. Swype is oversized so forces screen to be smaller  
Suggest that you resize to keyboard with every key press. Without workaround app is unusable

Bug

**Comment by sciencemanx** [comment]
If possible it would be good to turn off the kanji suggestions while in the app as this is kind of cheating an makes it hard to input the correct text.
