### ISSUE TITLE
Feature Request: "Longest Relative Wait" Order

### ISSUE THREAD

**Issue by SomeGuyNamedDavid** [davidsansome/tsurukame#355]
Your lowest-level items are the ones that need to be reviewed most frequently in order to remember them, so weighing all items’ time in the review queue equally will make it more likely to answer wrong on low-level items compared to high-level ones.

Instead, for example, say you order by ratio, and you have an Apprentice 4 item (2 day wait to review it) that’s been sitting in your queue for a week. That item’s ratio is 3.5 (7/2), as that’s how many times longer you’ve waited to review it than recommended.

Then, say you also have a Guru 1 item (1 week wait) that’s been in queue for a month, so it has a ratio of 4 (28/7). That item then, since it has a higher ratio, has spent a longer relative time in the queue than the Apprentice item, and thus would be reviewed first under ratio sorting rules.

**Comment by turtlemaster19** [comment]
Good idea! We should call it "longest relative wait" order in my opinion — more descriptive.

**Comment by SomeGuyNamedDavid** [comment]
Perfect, I was having trouble coming up with a good name to describe the concept with.

**Comment by turtlemaster19** [comment]
Here's a pull request! ;)

**Comment by SomeGuyNamedDavid** [comment]
Thanks for the prompt response, much appreciated!

**Comment by turtlemaster19** [comment]
@SomeGuyNamedDavid Please reopen until the PR is merged.

**Comment by SomeGuyNamedDavid** [comment]
Oops, can do. Sorry, thought they'd been merged already.
