### ISSUE TITLE
Switch keyboards automatically

### ISSUE THREAD

**Issue by kevananderson** [davidsansome/tsurukame#36]
Duolingo does this. When the answer is in Japanese, it switches to my Japanese keyboard, or at least the last one I used die Japanese. When English is required, it gives me English.

**Comment by davidsansome** [comment]
I thought a lot about this initially, and I actually wrote the code to do it.
But it doesn't work so well for Wanikani.  Japanese keyboards suggest the Kanji for the Kana that you're typing.  So, for example, if you type the letters h-i-t-o on Gboard in Japanese mode it'll show 人 as one of the suggestions in the top row, which is obviously cheating.
AFAICT it's not possible to tell the keyboard to only allow Kana input, and not suggest Kanji.

**Comment by turtlemaster19** [comment]
I think this was closed by #226.
