### ISSUE TITLE
値札 (price tag) vocabulary continually appearing in lessons

### ISSUE THREAD

**Issue by matschaffer** [davidsansome/tsurukame#366]
For some reason 値札 is stuck in my lesson queue even after doing it in “learn” many times. 

I’ve tried rebooting the phone and reinstalling the app but the issue persists. 

Is it okay to post a local database export here or should I email it to you?

Thanks in advance. Love the app! 🧡

**Comment by turtlemaster19** [comment]
@matschaffer This issue is already fixed, please use the TestFlight beta linked in the README and close this!

**Comment by matschaffer** [comment]
So far so good! Thanks!
