### ISSUE TITLE
Feature request: Random lesson order

### ISSUE THREAD

**Issue by marifly** [davidsansome/tsurukame#367]
In WK, there is a setting where you can choose to get lessons in order: "Ascending level then shuffled". I know that in Tsurukame I can choose the ordering of the lessons between radicals, kanji and vocab. Would it be possible to add an option go get the lessons shuffled too, like you can in WK?
![image](https://user-images.githubusercontent.com/65854762/85711157-4801ce80-b6e7-11ea-8e7b-66ffb20346fa.png)

**Comment by turtlemaster19** [comment]
@marifly Duplicate of #201. Please add your comment there instead of creating a new issue. And, yes, I already did it in my PR. ;)

**Comment by marifly** [comment]
Thank you! Closing this issue then. Looking forward to seeing this in Tsurukame!
