### ISSUE TITLE
Landscape view for wider keyboard on small screens

### ISSUE THREAD

**Issue by bmironer** [davidsansome/tsurukame#37]
Hello,
I just found out about this app and I'm giving it a shot to replace AlliCrab:

So far, it's fantastic and exactly what I needed!

One feature request I didn't see posted above though, if you ever have the chance to implement it : 

a usable landscape view on iPhone SE, so we can make use of the wider buttons,for easier typing and less typos.

- Shows the kanji, input field and keyboard, without scrolling, in landscape view.
- Scrolls automatically on the detail view when needed (on errors), 
while keeping the input field at the top (so the buttons are always available)

Thanks a lot!

**Comment by bmironer** [comment]
Also, the landscape view on iPad isn't resized properly.
On the 'new' 10" iPad, in landscape, the keyboard hides the input field
also the Kanjis could be both bigger and with smaller margins to save space.

**Comment by turtlemaster19** [comment]
I think this and #31 are actually the same problem, so we probably can safely close it.
