### ISSUE TITLE
Bug: Broken HTML in explanation of 妖 in lesson

### ISSUE THREAD

**Issue by Mercieral** [davidsansome/tsurukame#371]
Im seeing some weird HTML sneaking into this lesson page.

![7D3C6E15-2DE8-47FC-B9E9-CA2EFBC8B779](https://user-images.githubusercontent.com/10813646/86523657-eeab4500-be34-11ea-9424-dab1a82ad17e.png)

**Comment by turtlemaster19** [comment]
@Mercieral Issue on WK's side. See https://community.wanikani.com/t/妖-invalid-tags/44741
