### ISSUE TITLE
Feature Request: Show all meanings for a review even if you answered correctly

### ISSUE THREAD

**Issue by Takanu** [davidsansome/tsurukame#372]
Hey there, this app is fantastic and it makes using WaniKani far more enjoyable, but the oooooonly thing I miss from it is the fact that during reviews I can’t view all the meanings for a review when i’ve gotten it right - I often use this to ensure I remind myself of all the other possible meanings so I have a broad understanding of the particular Kanji or Vocabulary i'm reviewing and it’s something I really miss.

Adding the option to see all meanings for a review when answered before moving on would help me ensure I continue to have a more complete understanding of a Kanji or Vocabulary instead of just cementing the one easiest meaning in my mind.

**Comment by turtlemaster19** [comment]
@Takanu Please see #49.

If you think this would solve your problem, please close your issue and vote for it. If not, please explain.

**Comment by Takanu** [comment]
I think thats an important addition to make sure if you got the reading wrong but haven’t been tested on the meaning that it doesn’t spoil it for you.  However the problem this issue has is with **getting the reading right but not then being able to easily see all the potential meanings for that review**, to aid with memorizing all the possible ways a review item can be used.

As i’ve used to app ive noticed that once you complete both the meaning and reading of a review then you can tap it in the bottom-right to view the entire entry for it, which I think helps but isn’t as nice as just holding on the completed reading to just show you at the bottom all the readings (or meanings) that could have been used if more than one exists, before hitting enter or tapping the arrow to move onto the next one.

A compromise (at least for me as an iPad user) would be to add a key command for viewing the last completed review and a command for moving from that details page back to the review page, so at the very least I can move more quickly through my review, but I think having an option to show all possible answers before moving on is a more elegant solution to this problem

**Comment by UInt2048** [comment]
@Takanu Can you choose which of these is your request:

1. Disable lightning mode - even if you get the answer correct, show the pop-up like when getting it wrong
2. After a correct answer, have the last review completed pop-up appear all the time, so you can tap it and see additional meanings (assuming you have already given a correct meaning answer) or readings (assuming a correct reading answer)
3. Neither of these - I must be missing the point.

If you pick 3, please state clearly exactly what you want.
If you pick 2, see the Monster pull request where I already solved it.
If you pick 1, no more is needed.

**Comment by UInt2048** [comment]
This request could be interpreted one of two ways:

1. Disable lightning mode
2. Add key commands to the review view controller (perhaps 'p' for previous to show the subject details view, and 'h' to hide it)

**Comment by Takanu** [comment]
Sorry for not responding in a while and not being clear in my intentions.

The second one is the only one that sounds closest to what i'm looking for and would still be useful, but a better and more precise request would be to show all meanings of a question briefly before switching to the next review.

For example. say you get the Kanji for 本 and you respond with "Origin".  The review completes, but then you're briefly shown all possible answers (Book, Origin, Real, Main) so you're reminded that other possibilities exist while keeping the speedy pact of the review session.  Maybe like a little pop-up like the optional confetti and memorization rank that appears from below, only something that lasts a little longer so you have time to read the other possibilities that you didn't write down.

**Comment by UInt2048** [comment]
@Takanu The reason why I was wondering if you wanted to disable lightning mode is because that would mean that all answers would be shown, for as long as you need, just like on the site, and then you are able to move on when you're ready.

**Comment by Takanu** [comment]
Yeah, I understand why that would make sense as a suggested option.  The difference with disabling Lightning mode and the site however is that WaniKani only shows you the answer to the component you were answering (reading or listening) whereas  the information screen on Tsurukame shows everything... which makes it feel like im cheating if i see it all and haven’t answered the meanings yet.  

In effect it can rob me of the chance to have my memory tested which is why I don’t consider it a solution.

5 seconds sounds like the right amount of time, and I agree that the pop-up should immediately closed when something else needs to happen.

**Comment by UInt2048** [comment]
@Takanu The issue you have addressed above will be solved with #392

**Comment by Takanu** [comment]
It would solve the issue, although as you mentioned previously adding key commands to the Review View Controller would also be handy to this effect to keep reviews going smoothly on an iPad with keyboard attachment.
