### ISSUE TITLE
Add WK level to radical/kanji/vocab page

### ISSUE THREAD

**Issue by smearedink** [davidsansome/tsurukame#375]
Sometimes when I’m looking at a kanji I click through one of the component radicals, or similarly when looking at vocab I click through the component kanjis. Quite often I’m curious what WaniKani level these will be at (if I’m poking around at future items) or were at. It seems I only get to see this if I specifically search that item; then it shows up beside the search result.

Can you add an item’s WK level somewhere on the explanation page for the item itself?

(Alternatively: Is it available there already and I’m blind?)

EDIT: Just occurred to me that I would similarly enjoy (at least the option of) an SRS level indicator on the same page.

**Comment by UInt2048** [comment]
@smearedink See #257
