### ISSUE TITLE
Convert uppercase letters to katakana

### ISSUE THREAD

**Issue by hesch** [davidsansome/tsurukame#38]
Uppercase letters aren't converted to katakana. If the first letter of the typed romanization is uppercase, the kana should be converted to katakana otherwise to hiragana.

**Comment by boutmansb** [comment]
![image](https://user-images.githubusercontent.com/6972717/42630686-f65a4a2c-85d7-11e8-82f7-39f361b07e67.png)
Also when you use the japanese installed keyboard in ios to type in katakana, you cant see what you are typing.

**Comment by sciencemanx** [comment]
@boutmansb Thats kind of an unrelated separate problem. You should open up a separate issue.

**Comment by sciencemanx** [comment]
@boutmansb Actually your problem seems to be covered in issue #35
