### ISSUE TITLE
Bug: Testflight update reset settings

### ISSUE THREAD

**Issue by abdulajet** [davidsansome/tsurukame#388]
There have been a few builds for ver. 1.22 so I am not sure which one did it, likely 713 or 714 but my settings were reset to the default. Just a heads up

**Comment by UInt2048** [comment]
Absolutely was d67f84ba63c66e719ec4d49ae24d5b22fff62f10 if that happened.

**Comment by abdulajet** [comment]
lol yep that would be it!

**Comment by UInt2048** [comment]
@abdulajet Sorry about that, I guess the Swift conversion must have messed up something unfortunately. 😢

I don't think much can be done about it.

**Comment by abdulajet** [comment]
no worries! just wanted to mention it if it wasn't spotted already. that's what the testflight is for :)

**Comment by davidsansome** [comment]
I quickly checked that settings were preserved before merging that PR, but I didn't check everything.

@abdulajet do you remember which settings in particular were reset? Was it all of them or just some?

> I don't think much can be done about it.

Wiping settings on upgrade is unacceptable to me. We absolutely can do something about it - we can put in code to migrate values from the old serialisation format to the new serialisation format.

**Comment by abdulajet** [comment]
Just based on the ones i has changed:

- lesson batch size
- font size
- show japanese keyboard

**Comment by UInt2048** [comment]
I found the problem, on line 55 here for all types (derived from the old getter for objects), compared to 35 in the old getter for enums.

https://github.com/davidsansome/tsurukame/blob/86c415fa84c5e1a6aff0ca832e4fd8b69e48d4d0/ios/Settings.swift#L54-L58

https://github.com/davidsansome/tsurukame/blob/cfa3dc5aa0c7c0e91a15deb020ba350666ff7eae/ios/Settings.m#L33-L39

**Comment by UInt2048** [comment]
@davidsansome The safeguard works correctly. Can you close this issue?
