### ISSUE TITLE
New level but vocabulary already loaded

### ISSUE THREAD

**Issue by jonnzc** [davidsansome/tsurukame#401]
Hi. I have been using your app for a few years. I recently went from level 11 to 12 and with that transition a lot of the vocabulary items were immediately put in my reviews without having taken the lessons. As background to the situation I was previously on level 18 but had not studied for 6 months so when I came back I reset to level 10 and have been working upward from there. In the wanikani page none of those vocabulary items are listed for reviews so the database is not syncing it seems.

**Comment by UInt2048** [comment]
@jonnzc If you believe we need to investigate this, and you still can, please post the DB on GitHub (provided, of course, that you reset that API key)

If you don't think this is an issue any longer, please close it. Thanks!

**Comment by jonnzc** [comment]
Thanks for responding. Keep up the good work.
