### ISSUE TITLE
Lessons repeat

### ISSUE THREAD

**Issue by chonchosan** [davidsansome/tsurukame#409]
I'm at level 2 but can't advance with my lessons, everytime I finish a new lesson, it resets so I have to do it again.

**Comment by UInt2048** [comment]
@chonchosan Duplicate of #377.

Can you share your database (export database in Tsurukame's settings) here on GitHub, and _close_ this issue to avoid crowding out other issues?

**Comment by chonchosan** [comment]
Will do. Thank you.

[local-cache.db.zip](https://github.com/davidsansome/tsurukame/files/5220042/local-cache.db.zip)

**Comment by UInt2048** [comment]
Gotcha... it's a 422 error. Now I know what happened!

**Comment by chonchosan** [comment]
Great! Is there anything I can do to solve it?


Alonso Quiroz
PhD Student
School of Medicine
Pontificia Universidad Católica de Chile
