### ISSUE TITLE
Break line on reviews?

### ISSUE THREAD

**Issue by abdulajet** [davidsansome/tsurukame#411]
![image](https://user-images.githubusercontent.com/15106299/94452074-0c274b00-01a7-11eb-8252-a6fb0e92cfdc.jpeg)

I find that truncation is probably less than ideal for the case of this app. Any reason not to break onto two lines? If not i can submit a PR.

**Comment by UInt2048** [comment]
@abdulajet Please do submit a PR. It's already a bug (this is a duplicate of #313)

**Comment by abdulajet** [comment]
👍🏿

**Comment by UInt2048** [comment]
@abdulajet If at all possible, can you close _this_ issue since we already have it on the issue tracker at #313?
