### ISSUE TITLE
Missing ClockKit import?

### ISSUE THREAD

**Issue by giraffesyo** [davidsansome/tsurukame#412]
I cloned the repo and wasn't able to get it to build without adding a line `import ClockKit` to the top of SettingsController.swift

>/Users/giraffesyo/Development/tsurukame/ios/ComplicationExtension/SettingsController.swift:70:18: Cannot find 'CLKComplicationServer' in scope

The line it is referencing is this:

```swift
    let server = CLKComplicationServer.sharedInstance()
```

Is there a different trick or step I'm missing? I'm assuming the code in the repo works without adding this, so I'm puzzled what I missed.

**Comment by UInt2048** [comment]
That's correct - #407 addresses this already. I was hoping it would be merged sooner...
