### ISSUE TITLE
Is my "Time Remaining" calculated correctly? Over one year for level 2?

### ISSUE THREAD

**Issue by sbmelvin** [davidsansome/tsurukame#418]
I've been on level 2 for a couple days and the app says I have an estimated 463d 17h left. Surely that's a bug, right?

**Comment by UInt2048** [comment]
@sbmelvin Did you create your WK account around August 20, 2019 by any chance?

**Comment by sbmelvin** [comment]
@UInt2048 Yep, I created my account around that time and never touched it until now.
