### ISSUE TITLE
How can we support this project?

### ISSUE THREAD

**Issue by dbruehlmeier** [davidsansome/tsurukame#421]
I find Tsurukame highly useful! Thank you very much for making this app.

How can we support the future development of the project? The app is free and I feel there should be ways to help you at least cover your cost.

**Comment by UInt2048** [comment]
@dbruehlmeier You're not the first to ask. However, David Sansome has previously stated that this app will only receive contributions in code.

P.S. Please close this issue!

**Comment by dbruehlmeier** [comment]
OK, thanks for the quick reply!
