### ISSUE TITLE
On iOS keyboard doesn’t switch back to English for meaning questions

### ISSUE THREAD

**Issue by brentlongstaff** [davidsansome/tsurukame#422]
If you enable the option to switch to Japanese keyboard for readings, it doesn’t switch back when the next meaning question comes, leaving you with a kana  keyboard to type English words. This was not an issue until I reinstalled the app to resolve another issue but now I can’t get rid of this bug. I’ve tried reinstalling the app, removing and re-adding Japanese keyboard in iOS, restarting phone, toggling settings, etc.

**Comment by UInt2048** [comment]
Have you tried switching it back manually? It might be confused about which one it's supposed to switch back to ;)

**Comment by brentlongstaff** [comment]
I can switch back manually but I have to do it every time. Before I reinstalled it would alternate keyboards automatically which was great.

**Comment by UInt2048** [comment]
@brentlongstaff I know it's a long shot, but can you try the TestFlight build in the README here on GitHub?

**Comment by brentlongstaff** [comment]
The testflight page says "This beta isn't accepting any new testers right now." Do I need an invitation or something?

**Comment by UInt2048** [comment]
@brentlongstaff It means the ninety days has ended without being updated...

**Comment by ShaneCoufreur** [comment]
I am also seeing this behaviour after installing the current appstore version. I had to uninstall the Testflight build today, because the build expired. 
The Testflight build did not show this behaviour.

**Comment by UInt2048** [comment]
@ShaneCoufreur Thanks for the input.

**Comment by UInt2048** [comment]
@brentlongstaff See #426 - TestFlight is back up and running: please close this issue
