### ISSUE TITLE
Level completion estimation seems off

### ISSUE THREAD

**Issue by gethijsem** [davidsansome/tsurukame#423]
There’s something off with my estimated time for level completion. Not a necessary function by any means, but I like it. Is this the actual estimation (500+ days!)? I can’t imagine![05D23078-26BE-4302-91C7-8F78E928FFF4](https://user-images.githubusercontent.com/32223132/105342697-f4098a80-5be0-11eb-8658-da50139480ec.png)

**Comment by UInt2048** [comment]
@gethijsem Duplicate of #418.

Please see that issue for more information.

**Comment by gethijsem** [comment]
Figures, thanks.

**Comment by UInt2048** [comment]
@gethijsem No problem. Would you mind closing this?
