### ISSUE TITLE
Can't login with latest Test Flight build

### ISSUE THREAD

**Issue by carolinesweetpea** [davidsansome/tsurukame#425]
Getting a popup: Error, Incorrect username or password

Just downloaded the latest test flight build - using and password manager (1password), so pretty sure I have the correct username/password - tried manually typing it too, and verified that the login works on wanikani.com. Also deleted the app from my phone and re-installed afresh.

App store version does let me sign in (using the same credentials)

**Comment by davidsansome** [comment]
Yep I'm seeing this too, I'm looking into it now!

**Comment by davidsansome** [comment]
I think I fixed the bug - it should be in TestFlight in about 30 minutes!
