### ISSUE TITLE
Latest test build shows no lessons and reviews

### ISSUE THREAD

**Issue by marifly** [davidsansome/tsurukame#426]
In normal Tsurukame I have many pending lessons and reviews. In the TestFlight version I have none.
![6E13ECA5-62D4-4B1C-9A06-E3F0286708A9](https://user-images.githubusercontent.com/65854762/106379927-95e26180-63af-11eb-9350-a0db1fca3761.png)
![4AD3EBFD-08BB-434A-A087-1A65DB1B8498](https://user-images.githubusercontent.com/65854762/106379928-9975e880-63af-11eb-86cd-c5b87ae50971.png)

**Comment by davidsansome** [comment]
I see this too when installing a new build over the App Store build. Doing a full refresh (pulling down on the main screen) fixes it for me - can you try that?

If it doesn't work can you export your database (tap Settings then scroll to the bottom then "Export local database") and email it to me@davidsansome.com?

**Comment by marifly** [comment]
Refresh did not fix it, close the app did not fix it, reinstall did not fix it. I’ll send you my database!

**Comment by abdulajet** [comment]
sent over my local database too, i've got the same problem

**Comment by UInt2048** [comment]
I'm still logged in, so not experiencing this problem. However, there is a discrepancy of one review, likely due to an out-of-date database.

**Comment by UInt2048** [comment]
Weirdly, it was fine, and then it showed an update to build 776, and after hitting update, said problem appeared.

**Comment by davidsansome** [comment]
Thanks for all the databases! I think I figured out. New testflight build hopefully coming soon, if I can fix the codesigning issues too!

**Comment by UInt2048** [comment]
@davidsansome It looks like those issues were fixed in 8bbf6f5410273e14725a0a4a332c202642c6e651 - I just downloaded the build on TestFlight! 🎉

**Comment by davidsansome** [comment]
Fantastic, thanks for confirming!

**Comment by UInt2048** [comment]
@davidsansome No problem - glad it's all working now! 🎉

(Maybe we could even get an App Store release soon - it's severely out of date at seven months behind!)

**Comment by davidsansome** [comment]
Yep that's the plan!

**Comment by marifly** [comment]
Since I opened this issue, I just wanted to confirm that it works now for me too!
