### ISSUE TITLE
Support for Wanikani hotkeys during reviews 

### ISSUE THREAD

**Issue by matchai** [davidsansome/tsurukame#428]
Hey Tsurukame maintainers! 👋 

I'm loving the app and use it daily for my lessons and reviews on my iPad with keyboard accessories.
By default, the most important keys already function as you would hope: arrow keys and return navigate between lesson pages.

It would be nice if we could have support for the full gamut of Wanikani hotkeys:

**Lesson Slides**
- <kbd>A</kbd> or <kbd>←</kbd> Move back a slide/item
- <kbd>D</kbd> or <kbd>→</kbd> or <kbd>Return</kbd> Move forward a slide
- <kbd>Q</kbd> Start quiz
- <kbd>J</kbd> Audio pronounciation

**Lesson Quiz**
- <kbd>J</kbd> Audio pronounciation

**Comment by UInt2048** [comment]
@matchai Would you mind testing #429 which attempts to do this?

**Comment by UInt2048** [comment]
@matchai I have confirmed #429 implements this - tested on iPad6,3
