### ISSUE TITLE
Incorrect number of reviews and start date

### ISSUE THREAD

**Issue by fufu78** [davidsansome/tsurukame#43]
![img_7132](https://user-images.githubusercontent.com/40305354/41487169-72a79228-70df-11e8-9c8d-6fcbee421aaa.PNG)

I currently have 0 reviews.

**Comment by ezrabenson** [comment]
I have this same issue as well, 48 years and 1500 reviews.
It looks like it is taking all the reviews I will have in the future and letting me do them now. For example if I have an enlightened item which will come up for review in 2 months, it just adds that to my current review queue.

**Comment by davidsansome** [comment]
I need some help debugging this!  If anybody has a few minutes I'd appreciate if you could do two things:

1. Go into Tsurukame's settings (cog icon in the top-right) and select "Export local database".  That'll create a file that you can share via email with me@davidsansome.com.

2. Also go to the iOS settings, "General", then "Date & Time", and check the date is correct.  If you have "Set Automatically", turn that off so you can see what date your phone thinks it is, and check that is correct.

**Comment by fufu78** [comment]
I don’t know what happened but I just logged into the app and I am no longer having this issue. It is giving me the correct reviews and start date.

**Comment by ezrabenson** [comment]
I still have this issue, I have sent my database to the email requested and also changed my time settings

**Comment by davidsansome** [comment]
This should be fixed in the latest version
