### ISSUE TITLE
No button to close review summary

### ISSUE THREAD

**Issue by marifly** [davidsansome/tsurukame#430]
I did my reviews and got a review summary. I think there used to be a button here that I could use to close the screen and get back to the main screen. Now I can’t see a button. I had to close the app to get out.

![315BA43F-3EFB-420A-828D-FAE55C0C8D97](https://user-images.githubusercontent.com/65854762/108161144-b9651600-70ea-11eb-9a0a-40b42f4b6138.png)

**Comment by davidsansome** [comment]
Oops this was my mistake. Thanks for finding it!
