### ISSUE TITLE
Show remaining review times missing

### ISSUE THREAD

**Issue by abdulajet** [davidsansome/tsurukame#431]
not sure if this is intentional but the show remaining rows have changed. 

before:
![image](https://user-images.githubusercontent.com/15106299/108335508-f56fa800-71ca-11eb-9307-010ea44765a9.png)

now
![image](https://user-images.githubusercontent.com/15106299/108335569-04eef100-71cb-11eb-89d7-3914a9209cbb.png)

**Comment by davidsansome** [comment]
Oops that was a typo in the Swift conversion (bdd4918aec81b300571898e010c77be733fe1f0d) Thanks for noticing it!

**Comment by abdulajet** [comment]
cheers!
