### ISSUE TITLE
The level numbers on the review summary screen are all wrong

### ISSUE THREAD

**Issue by marifly** [davidsansome/tsurukame#432]
I did my reviews and got to the review summary screen. Every item I got wrong is marked with the right level number, but the «headings» over each level are wrong. It says Level 22 on all of them.

![14741726-383B-484D-B451-1F82D96B4E46](https://user-images.githubusercontent.com/65854762/108887564-b7c7b080-760a-11eb-80c5-ac69c941d9fb.jpeg)

**Comment by UInt2048** [comment]
@marifly Are you currently at Level 22?

**Comment by marifly** [comment]
> @marifly Are you currently at Level 22?

Yes, I am.

**Comment by davidsansome** [comment]
Oops my fault again. Thanks again for finding these bugs!

**Comment by marifly** [comment]
> Oops my fault again. Thanks again for finding these bugs!

Thank you for making Tsurukame!
