### ISSUE TITLE
Review times seem wrong

### ISSUE THREAD

**Issue by abdulajet** [davidsansome/tsurukame#434]
This might be an issue on the wanikani side but i have a kanji on a different SRS level that says it will be completed at the same time as the kanji on the above level. ![image](https://user-images.githubusercontent.com/15106299/109632310-cd733380-7b3e-11eb-86ee-f9e827648a4a.jpeg)

**Comment by UInt2048** [comment]
@abdulajet No, because of the guru in date, we can tell it's an issue on Tsurukame's side.

In fact, my times are backwards - I have Apprentice I stuff that says Guru in seven hours, and III stuff in 1d 22h.
