### ISSUE TITLE
Attempting to log in with a password containing an & fails, because the & breaks the arguments in the web request.

### ISSUE THREAD

**Issue by ShaneCoufreur** [davidsansome/tsurukame#436]
When attempting to log in with a password containing the character &, the login request fails.
This seems to be happening because the data in the HTTP body is not encoded.

Cause of the issue appears here:
https://github.com/davidsansome/tsurukame/blob/0060ec8b352cbc3216c2b69588c0171826d4d7d6/ios/WaniKaniAPI/WebClient.swift#L101

I'm unable to change and test this myself, as I don't have a working dev env set up on a mac.
I did do some testing and think this might, potentially, solve it.
Changing:
```
      // Build the login request.
      let queryItems = [
        URLQueryItem(name: "user[login]", value: username),
        URLQueryItem(name: "user[password]", value: password),
        URLQueryItem(name: "user[remember_me]", value: "0"),
        URLQueryItem(name: "authenticity_token", value: csrfToken),
        URLQueryItem(name: "utf8", value: "✓"),
      ]

      var req = URLRequest(url: kLoginUrl)
      req.httpShouldHandleCookies = true
      try req.setFormBody(method: "POST", queryItems: queryItems)
      return request(req, session: session)
```

into

```
        var req = URLRequest(url: kLoginUrl)
        req.httpMethod = "POST"
        req.setValue("application/x-www-form-urlencoded;charset=UTF-8", forHTTPHeaderField: "Content-Type")

        var urlComponents = URLComponents()
        urlComponents.queryItems = [
          URLQueryItem(name: "user[login]", value: username),
          URLQueryItem(name: "user[password]", value: password),
          URLQueryItem(name: "user[remember_me]", value: "0"),
          URLQueryItem(name: "authenticity_token", value: csrfToken),
          URLQueryItem(name: "utf8", value: "✓"),
        ]
        request.httpBody = urlComponents.percentEncodedQuery?.data(using: .utf8)
        return request(req, session: session)
```

Again, I'm not 100% sure this fixes it because I can't test this locally myself, but I'm hoping someone who does have a working setup can build on this suggestion.

**Comment by UInt2048** [comment]
Close - the second-to-last line in your fix should have assigned to `req.httpBody` not to `request` which is a function.

**Comment by ShaneCoufreur** [comment]
@UInt2048 Thanks for checking the code and testing it.
I missed the typo because of some renaming I did after pasting it in markdown and not property checking it.

**Comment by UInt2048** [comment]
@ShaneCoufreur No problem... except afterwards, I was not able to log into my main account without an ampersand in the password.
