### ISSUE TITLE
Cannot Log in

### ISSUE THREAD

**Issue by Usagi99** [davidsansome/tsurukame#442]
I recently made a wanikani account on the website. However, on the app I cannot log into it. The app gives me a log in error that says “API token not found”.

**Comment by UInt2048** [comment]
@Usagi99 Try going onto the website into the API tokens section of the Settings, and adding one called Tsurukame with full permissions

**Comment by davidsansome** [comment]
Sorry about this!

I fixed the bug in f8e1164262d04b6f90b8d8ca91e1a8d44c80c39c.

Version 1.22.1 contains the fix and should be available in the App Store some time this week!
