### ISSUE TITLE
Items show up in “Show remaining” in the wrong SRS section

### ISSUE THREAD

**Issue by TurtleCat02** [davidsansome/tsurukame#443]
![7002483A-661A-4BED-A23E-48B1EFA70584](https://user-images.githubusercontent.com/35201253/113043873-0e289180-916b-11eb-8ea9-e766fa6f2a4c.png)
![5397E8E8-3831-4150-875B-9B2166F0F373](https://user-images.githubusercontent.com/35201253/113043878-0ff25500-916b-11eb-9c0c-c9127ef2249c.png)
![420F1422-BBF2-4286-B4FE-87A1400D7069](https://user-images.githubusercontent.com/35201253/113043885-11238200-916b-11eb-9586-92689293ee10.png)

Some of the items in “Show remaining” show up in the wrong section, for instance, in the first image, there are two terms that are part of the “locked” section when they are not locked. This happens for different levels as well, in the second and third images, the term 共 is part of the Apprentice III section, but it’s time and stats show it as being a part of Apprentice IV

**Comment by UInt2048** [comment]
@davidsansome The items out of the proper "separator item"-bounded section are always first, leading me to believe that it's a bug in `SubjectsRemainingViewController`.

**Comment by abdulajet** [comment]
@UInt2048 did you have a chance to look into this?

**Comment by UInt2048** [comment]
@abdulajet Thanks for the reminder. I'll see maybe tomorrow if I can find out what's causing this.
