### ISSUE TITLE
Hirobaba changed to Katakana

### ISSUE THREAD

**Issue by saritapapow** [davidsansome/tsurukame#445]
is:issue is:open many hiragana words have become katakana. The app also forces me to type those words in katakana. The app thinks these answers are correct. For example: West is originally せい。 but the app forces the user to type セイ. The system accepts this as a correct answer.
![E472E31B-508A-4278-A90E-0956C94FA0BD](https://user-images.githubusercontent.com/78827923/113493489-a089b600-951a-11eb-912b-10b6082a58dd.jpeg)

**Comment by davidsansome** [comment]
Oops it looks like the default for the "Use Katakana for onyomi readings" was changed from off to on in d67f84ba63c66e719ec4d49ae24d5b22fff62f10.

You should just be able to go into the app's settings and change it back for now.
