### ISSUE TITLE
Feature Request: Offline self-study quizzes

### ISSUE THREAD

**Issue by jleskovar-tyro** [davidsansome/tsurukame#446]
Generalised version of #332 - it would be great if there was a way to initiate self-study quizzes, similar to the website userscript, and ideally while offline. (As as an aside - I spend a lot of hours on the train with spotty network, so to me this would be an absolute killer feature, that I'd happily fork out 💰 for).

**Comment by UInt2048** [comment]
This issue would also logically track any similar request for the newly added “extra study” mode to the site
