### ISSUE TITLE
Tsurukame problem 

### ISSUE THREAD

**Issue by Haris-senpai** [davidsansome/tsurukame#448]
Is there a way to turn the Wanikani stats off. And also is this a bug? Why doesn’t it show the member kanji as visually similar when looking at the buy kanji. I’ve looked at other kanji’s and it is also the same with them. Not all. But most 
![AAEFD607-AEC5-44F3-A63F-AF0C47F8ED2E](https://user-images.githubusercontent.com/82033764/113705617-a6fb6780-96ab-11eb-914f-06ffbc7ed0aa.png)

**Comment by UInt2048** [comment]
@Haris-senpai The website doesn't show that kanji as visually similar. You should ask WaniKani about it.

Also, why would you want to turn the stats off?

**Comment by Haris-senpai** [comment]
Because it’s in the way. Personally for me I don’t need to know the stats. Is there a way to toggle it off? It is very redundant when I know what level I’m already on, and then at the bottom it says that level

**Comment by Haris-senpai** [comment]
@UInt2048 is that then a problem on Wanikani’ side then yours?

**Comment by Haris-senpai** [comment]
@UInt2048 another example 
![9663486A-D064-40F2-AFEE-0352EAA5E5F3](https://user-images.githubusercontent.com/82033764/113706560-d363b380-96ac-11eb-9c6f-0c44f0bc6864.png)

**Comment by UInt2048** [comment]
@Haris-senpai The visually similar kanji part is a problem on WaniKani's side.

**Comment by Haris-senpai** [comment]
@UInt2048 and for the stats. Can their be an option to turn it on or off?

**Comment by UInt2048** [comment]
@Haris-senpai Yes, that shouldn't be too hard to add. I'll create a pull request in about an hour which would add it...

**Comment by Haris-senpai** [comment]
@UInt2048 Thank you so much

**Comment by UInt2048** [comment]
@Haris-senpai #449 will add this option.

**Comment by Haris-senpai** [comment]
@davidsansome @UInt2048 I contacted Wanikani support and here’s what they had to say. I think it’s a problem on your side because the app obtains the base information from Wanikani and if it’s inputting kanji that aren’t similar then, maybe it’s a problem with the app? 
![67BD6F97-EAD6-49C6-BEED-64B311B49C05](https://user-images.githubusercontent.com/82033764/113754221-00c85580-96dd-11eb-851a-4f5c45a85fa0.jpeg)
![11F8A29C-173D-45F0-9986-9A3DC605E450](https://user-images.githubusercontent.com/82033764/113754231-045bdc80-96dd-11eb-89fd-c94a22f7967b.jpeg)

**Comment by UInt2048** [comment]
@Haris-senpai We have a second list too with extra similar kanji - see the `similar_kanji` folder in the code about that. That seems to be the case here.

In addition, WK occasionally updates the similar kanji list. Perhaps both of these were the case for that second example.
