### ISSUE TITLE
Unable to input づ (zu)

### ISSUE THREAD

**Issue by jleskovar-tyro** [davidsansome/tsurukame#457]
Just hit level 7, and one of the vocab words I've come across is the word "handmade" 手作り, the WK reading of which is てづくり

Only issue is, Tsurukame's key input transforms "zu" to ず, with no other way to enter the correct input other than using IME directly.

**Comment by davidsansome** [comment]
Try typing "du" instead!

https://community.wanikani.com/t/how-to-type-%E3%81%A5/33891

**Comment by jleskovar-tyro** [comment]
🤦‍♂️ thanks, should have searched online first
