### ISSUE TITLE
Visually similar kanji are somewhat random and completely wrong (1.22.2)

### ISSUE THREAD

**Issue by einholen** [davidsansome/tsurukame#461]
When I noticed it the first time (I think it was showing 八 as similar to 人), I could see some similarity between the two kanji, but today I stumbled upon a couple more examples that are completely off - and even found some sort of pattern I think.

Examples I'm seeing in my app currently:
今 - 八
戸 - 切
九 - both 切 and 八
万 - 切

While showing wrong ones, it's not displaying actually similar kanji (大/犬, 万/方 etc)

I thought it could've been a WaniKani bug, but the web version doesn't seem to have this issue.
万 (correctly showing 方) https://www.wanikani.com/kanji/%E4%B8%87
今 (showing nothing) https://www.wanikani.com/kanji/%E4%BB%8A　
戸 (showing nothing) https://www.wanikani.com/kanji/%E6%88%B8
大 (showing 犬 and 太) https://www.wanikani.com/kanji/%E5%A4%A7

Some pics for wrong similar kanji:
<img src="https://user-images.githubusercontent.com/968700/117321818-7568ee00-ae5b-11eb-9bc9-2c0c85753584.png" width="200"> <img src="https://user-images.githubusercontent.com/968700/117321844-7a2da200-ae5b-11eb-93b5-47887bbada3c.png" width="200"> <img src="https://user-images.githubusercontent.com/968700/117321862-7dc12900-ae5b-11eb-9c61-1a9aef521bd8.png" width="200">

Some pics for missing similar kanji:
<img src="https://user-images.githubusercontent.com/968700/117322726-430bc080-ae5c-11eb-9936-fb30b6f53e86.png" width="200"> <img src="https://user-images.githubusercontent.com/968700/117323075-93831e00-ae5c-11eb-909e-2b9bc9400f23.png" width="200">

**Comment by UInt2048** [comment]
@einholen Can you please close this - it's a duplicate of #451.

If you want, you can see the discussion at #448 as well.

**Comment by einholen** [comment]
@UInt2048 thanks, I saw #451 but didn't quite realize that it was the same.
