### ISSUE TITLE
Meaning/Reading are randomly not shown

### ISSUE THREAD

**Issue by qdoot** [davidsansome/tsurukame#463]
![2054A130-1C8C-4EB1-BC77-A2CB9090E212](https://user-images.githubusercontent.com/22297268/117960689-8adb8d80-b31d-11eb-840f-e19d42160211.png)

Since the last update, occasionally, the reading explanation or the meaning explanation is not being shown. (As it can be seen in the image, only the reading explanation is being displayed)

**Comment by UInt2048** [comment]
Yes, that's because you haven't answered the meaning yet. It's not random.

However, there's already a fix for it in #458, if it will ever get merged. 😜
