### ISSUE TITLE
Synch problem. Now stuck with 150 reviews

### ISSUE THREAD

**Issue by marusiaside** [davidsansome/tsurukame#464]
Number of reviews suddenly dropped. I reported to WaniKani community but nobody guessed that this could be due to sync problem. Today I had 11 recviews. Then I deleted app, reloaded from AppStore and found 144 reviews waiting fir me.
![8C6B7EF9-6BF2-41D1-9A00-9864462415A4](https://user-images.githubusercontent.com/84742193/119400775-8e362800-bcd2-11eb-8ec0-77e5419f9f88.png)
![519BAF18-79D2-4851-A576-A654CCF34A02](https://user-images.githubusercontent.com/84742193/119400784-90988200-bcd2-11eb-8b44-82bfd0d039c3.png)

**Comment by UInt2048** [comment]
It's a shame the records were probably destroyed when you reinstalled the app.

Does it work properly now?

**Comment by marusiaside** [comment]
It works well now but I work full time and don’t have time for 150 reviews. It probably needs 3hr a day to finish.

**Comment by UInt2048** [comment]
@marusiaside Ah, well that's not exactly a Tsurukame problem. (I have over 1,500 reviews right now - I might need to reset.)

Would you mind closing this issue then?

**Comment by marusiaside** [comment]
Tsurukame Is the reason I have 150 reviews. 
For the two last week there was no sync going on. As a result my reviews dropped and I was mostly doing lessons. By the time I realised the problem and fixed it by reinstalling the app - reviews accumulated too much.
I am going to close but please put on the backlog adding the date of last sync to main screen as one of the options to notify people about potential issue.

**Comment by UInt2048** [comment]
@marusiaside Do you remember if during those two weeks, the pink bar that showed Tsurukame refreshing completed and disappeared like normal?

**Comment by marusiaside** [comment]
I see now that the pink bar is moving.
But I did not notice it previously. 
Will be paying more attention to pink bars in the future :-)
I will let you judge if my case is a common problem and needs further improvements.
Thank you
Closing the issue
