### ISSUE TITLE
Sync issue after wanikani site was down

### ISSUE THREAD

**Issue by EtzAlex** [davidsansome/tsurukame#469]
This morning wanikani's [backend went down](https://community.wanikani.com/t/i-cant-use-wanikani-rn/52003) and this happened to be at the time I was studying new kanji for my level. I was able to do reviews and lessons just fine (I assume due to the offline mode of tsurukame), and it was all synced to wanikani just fine once their site came back up. However, now my app homepage is essentially empty.

![IMG_6597](https://user-images.githubusercontent.com/11432227/122128629-cb7d6980-cde9-11eb-8000-515242d6cbb8.jpg)

Pull-down refresh shows the bar going across the screen, but nothing happens when it is done. I have tried logging out and logging back in on the app, but that has not worked. I tried reinstalling the app, but that also did not work.

**Comment by UInt2048** [comment]
The app works correctly for me. Try installing the beta version found in the README and see if that helps!

**Comment by EtzAlex** [comment]
It seems the issue has been solved by waiting a few hours, as everything seems synced up now. I'll close this up.
