### ISSUE TITLE
Sort lessons by Level

### ISSUE THREAD

**Issue by Goombario** [davidsansome/tsurukame#47]
Currently, when you unlock a new level you have to do all of the available lessons for that level before you can do the remaining lessons for the level you just finished. So if I levelled up from 5 to 6 but had vocab lessons remaining in 5 I can't access them until I've done all the level 6 lessons available. It would be great if we could have the option to complete the lower level lessons first.

Been using this app since launch, it's awesome!

**Comment by davidsansome** [comment]
Thanks for the feedback!
I fixed this already in ec13129cc3e89d2ca8b790647402198e753e4cf0 - it'll be in the next update, which should be real soon now!
