### ISSUE TITLE
Review option: pause on partially correct answers

### ISSUE THREAD

**Issue by davidsansome** [davidsansome/tsurukame#48]
Add an option to, when an answer is partially correct, stay on that answer and let the user look at the correct answer.

**Comment by indirect** [comment]
It would also be cool to show a little "warning!" icon the way the webapp does, so that even if it doesn't pause on that word, there's a way to see that the answer was not quite right, and then tap to see what the fully correct answer was.

**Comment by turtlemaster19** [comment]
It would be even cooler if there was a mark **incorrect** feature if the user sees that they have actually got the wrong answer, such as typing the f-word in frustration for not knowing what the kanji was, but it was 運

**Comment by turtlemaster19** [comment]
Optionally, there could also be a mark incorrect as well if the user believes the answer was wrong.
