### ISSUE TITLE
ipad shortcuts for anki mode

### ISSUE THREAD

**Issue by abdulajet** [davidsansome/tsurukame#489]
Loving the new anki mode very helpful as i cannot type much sometimes. Would be great to have some ipad shortcuts. The current one (CMD+C) doesn't work since it brings up the context menu which has the focus/first responder

**Comment by UInt2048** [comment]
@abdulajet Good idea. I'll try to look into that. 👀

**Comment by UInt2048** [comment]
@abdulajet I added a PR that adds a control-C synonym for the command-C mark-correct shortcut, as well as a new control-I/command-I shortcut to mark wrong.

**Comment by abdulajet** [comment]
Thanks :)

**Comment by abdulajet** [comment]
![image](https://user-images.githubusercontent.com/15106299/125702098-facf2b86-018c-4a15-9c77-6c14eeac3656.jpeg)

the shortcuts aren't working because the context menu is presented by default when you press enter on iPad + KB.
