### ISSUE TITLE
Review option: separate the meaning and reading answers

### ISSUE THREAD

**Issue by davidsansome** [davidsansome/tsurukame#49]
Currently the subject details view shows everything about the subject.
There should be an option to just show the relevant part - for example if you got the reading wrong, it should just show the reading.

Then we could make the answer fly to the button on the bottom-left after each correct task, and pressing the button would only show the partial information if you've only answered part of the subject.

**Comment by turtlemaster19** [comment]
@davidsansome, couldn't this or number 172  be closed now?
