### ISSUE TITLE
Context menu opens automatically when clicking continue on iPad + external KB + Anki mode

### ISSUE THREAD

**Issue by abdulajet** [davidsansome/tsurukame#494]
![image](https://user-images.githubusercontent.com/15106299/125702098-facf2b86-018c-4a15-9c77-6c14eeac3656.jpeg)

the shortcuts aren't working because the context menu is presented by default when you press enter on iPad + KB.

_Originally posted by @abdulajet in https://github.com/davidsansome/tsurukame/issues/489#issuecomment-880257421_

**Comment by abdulajet** [comment]
Looks like stopping the presentation when Anki mode is on fixes it:

```
    if !Settings.ankiMode {
      present(c, animated: true, completion: nil)
    }
```

Only problem is that you only want to so this when there is an external keyboard, is there some keyboard handling code in the app already? 

Found this on SO but seems a but meh https://stackoverflow.com/a/32338430

**Comment by abdulajet** [comment]
Also without an external keyboard, it seems to still present from where the synonym button used to be. This should probably be moved too but I cannot see where the placement of the presentation is calculated.

**Comment by UInt2048** [comment]
> I cannot see where the placement of the presentation is calculated.

https://github.com/davidsansome/tsurukame/blob/23f7999b9e26225f47c1e5ad744087b37e101767/ios/ReviewViewController.swift#L1264-L1265

**Comment by UInt2048** [comment]
> Found this on SO but seems a but meh https://stackoverflow.com/a/32338430

You also have the Mac Catalyst problem - Mac always has a physical keyboard (not touch) interface.

**Comment by UInt2048** [comment]
> Found this on SO but seems a but meh https://stackoverflow.com/a/32338430

That code could work... if we weren't in Anki mode. Since we are, the keyboard never shows, so code in `keyboardWillShow(notification:)` will never run.

**Comment by UInt2048** [comment]
One solution to this conundrum might actually be a setting not to open the context menu automatically.

(I know how to disable it, since I deliberately introduced that as a feature.)

**Comment by abdulajet** [comment]
aha yeah a setting would be a bit clunky but i am not sure we have a choice!
