### ISSUE TITLE
Can’t advance lessons on iPhone 8/iOS 11

### ISSUE THREAD

**Issue by dwnkg** [davidsansome/tsurukame#51]
The keyboard blocks the space to advance the reviews and lessons as well as their information if a user answers a question incorrectly.

**Comment by dwnkg** [comment]
Just noticed that this was for a specific word just noticed that this actually does work, but not for two words that I was testing. I’ll post them if I come across them again. Sorry for the mistake.

**Comment by davidsansome** [comment]
Are you switching from an English keyboard to a Japanese keyboard, and the Japanese keyboard is bigger than the English one so it's overlapping the input field?

You should be able to enter むっつ by typing "mottsu" or "mottu".

**Comment by dwnkg** [comment]
Yeah, I think there was some weirdness with the answer getting obscure and
the fact that I couldn’t find a good explaination for furigana online.

Thanks so much for “tts” example, I still didn’t know how to do that.

**Comment by turtlemaster19** [comment]
Is this still an issue now, or can it be safely closed. What do you think, @davidsansome?

**Comment by dwnkg** [comment]
It can be safely closed. Things are working perfectly for me now, thanks!

**Comment by turtlemaster19** [comment]
Okay, there should be a close button on the GitHub site. Thanks for responding! ;) Hope that your WaniKani experience is going well now.
