### ISSUE TITLE
Level 16 page kanji won’t accept correct answers

### ISSUE THREAD

**Issue by TheMandalorian42** [davidsansome/tsurukame#521]
Level 16, the page kanji 頁 won’t accept ページ as the correct answer, whether manually entered or copy/pasted from the kanji description.
Further, when learning the kanji, when it asks for the Kana it defaults to hiragana but won’t accept ぺーじ as an answer. Since it’s in the quiz to learn the kanji, I can’t manually add a “synonym” as the correct answer. 
currently blocked from progressing as I can never actually “learn” the kanji.
Two screenshots added showing hiragana and katakana answers not being accepted
![A528B8C8-C78F-42E9-B4F6-A66769E42C31](https://user-images.githubusercontent.com/93744225/140431381-64ada931-25bd-4f78-994b-f9a1c303d999.png)
 
![20B3AD52-A37B-4B0B-A4BA-FDE951AB7415](https://user-images.githubusercontent.com/93744225/140431375-25033af1-866e-4ea6-b26a-cf3a271439dd.png)

**Comment by starhill-sf** [comment]
This is level 10, but otherwise this is affecting me as well.

**Comment by TheMandalorian42** [comment]
Very strange - I’m level 16 and this is the first time I REMEMBER seeing this kanji haha. First time I’ve encountered the error, if I learned it at level 10 I didn’t get the error.
What else is strange is that I’ve learned all of the level 16 kanji (ie the middle circle is full) yet this is showing up as a new kanji to learn.

**Comment by starhill-sf** [comment]
Indeed, the Tofugu team adds things at a pretty good clip! Sometimes things get moved around too, so you might end up starting later levels with a head start on a few items.

**Comment by TheMandalorian42** [comment]
Very strange, thanks for the info though.
I logged into my wanikani and it’s definitely there as a level 10 but I didn’t learn it haha. My wife said she hadn’t seen it before either and she’s level 11 or 12.
I tried adding ぺーじ as a synonym to get past “learning” it but it still didn’t accept my answer. Now I truly am at an impasse haha.

**Comment by TheMandalorian42** [comment]
Wife is a smarty pants and suggested I do my review on wanikani instead of in the app. So at least now I have successfully “learned” the kanji and can progress haha.
I guess whenever it comes up for review though I’ll have to “cheat” and tell it my answer was correct. Seems like the readings it’s looking for is pulling from the wrong field though given that copy/pasting ページ wasn’t even accepted.
Problem remains, but work stoppage averted.

**Comment by davidsansome** [comment]
Thanks for reporting this bug! I'll look into it later today and see if I can figure out why it's not accepting ページ as the correct answer.

**Comment by maverick3683** [comment]
I am having this issue as well! I also did the workaround and “learned” it on wanikani in web browser. How do you “cheat” and say it’s correct? Is that a setting somewhere? Anyway, glad it wasn’t just me being silly I thought I was going crazy, and glad it’s being looked into! (ps, it didn’t work in Jakeipuu either, strange!)

**Comment by UInt2048** [comment]
@davidsansome I noticed that the alternate reading ぺーじ isn't present in the screenshot.

I just went on build 870, disabled Anki mode, and entered the reading without issue.

<details>
<summary>Recording Proof</summary>

https://user-images.githubusercontent.com/46784000/140496026-aac9956a-dae0-43f0-8d0d-fb270b0691ee.MP4

</details>

This is the fault of the issue #520, that I believe is fixed. Without the second reading, this won't work:

https://github.com/davidsansome/tsurukame/blob/master/ios/AnswerChecker.swift#L128-L150

**Comment by UInt2048** [comment]
@davidsansome I noticed that the alternate reading ぺーじ isn't present in the screenshot.

I just went on build 870, disabled Anki mode, and entered the reading without issue. (The alternate reading was present for me.)

<details>
<summary>Recording Proof</summary>

https://user-images.githubusercontent.com/46784000/140496026-aac9956a-dae0-43f0-8d0d-fb270b0691ee.MP4

</details>

This is the fault of the issue #520, that I believe is fixed. Without the second reading, this won't work:

https://github.com/davidsansome/tsurukame/blob/245fb0ccfa7bafadae27dfe8c8b937800487b5f1/ios/AnswerChecker.swift#L128-L150

**Comment by TheMandalorian42** [comment]
@maverick3683 , in the options you can “allow cheating.” Essentially when you’re doing your regular reviews there is a little plus icon on the left side once you answer and it gives you the option of adding a synonym, my answer was correct, and one other that currently escapes me.

looks like @UInt2048 may have solved it, though it’s a bit beyond me this early in the morning. I’ll have to come back once I’m actually awake haha.

**Comment by TheMandalorian42** [comment]
@UInt2048 should have just waiting 10 minutes to respond haha - yeah you’ve done it. I just did a review, saw additional readings in there, and ぺーじ was accepted, no cheat necessary.
Thank you!

**Comment by davidsansome** [comment]
It looks like that vocabulary was updated by Wanikani yesterday to include the hiragana reading as an accepted answer - it's got an updated date of 2021-11-05 11:03:14 UTC which was about 12 hours ago if my timezone math is correct! So there's nothing else for us to fix here \o/

@UInt2048 #520 is unrelated - that's about the list item getting the wrong size for the text and truncating the end of the string. It wouldn't affect answer checking.

**Comment by UInt2048** [comment]
@davidsansome Good catch, I didn't think about looking up the item to see if the item itself had changed. Regardless, glad to see this taken care of!
