### ISSUE TITLE
Remove synonym 

### ISSUE THREAD

**Issue by starhill-sf** [davidsansome/tsurukame#523]
Hello, sorry if this is obvious but I couldn’t find an answer by browsing/searching. Is there a way to remove a synonym that I added accidentally?

**Comment by UInt2048** [comment]
This is a duplicate of #169.

Could you please close this?

**Comment by starhill-sf** [comment]
Thanks! And sorry for the noise.

**Comment by UInt2048** [comment]
It's okay. Sorry that Tsurukame still isn't more helpful in this regard.

**Comment by starhill-sf** [comment]
> It's okay. Sorry that Tsurukame still isn't more helpful in this regard.

No problem! I wouldn't have even known about the WK feature if I hadn't found it through Tsurukame.

Thank you for the amazing work!
