### ISSUE TITLE
Tsurukame gone crazy

### ISSUE THREAD

**Issue by Mayasounds** [davidsansome/tsurukame#525]
Hi, I can’t help but describe it this way: my tsurukame has gone crazy recently. It doesn’t show reviews that need to be done, when I log out and in again it suddenly shows lots of new ones. But sometimes when I log out and in, it says ‘your account is in vacation mode’ and doesn’t show anything at all. 

Have tried to delete and reinstall/all the usual tricks but it keeps randomly not showing reviews and I keep having to log out and in again. Any more things to try? I’m on an iPhone 8, getting a new one in a few weeks so I’m hoping that’ll solve the issue if nothing else.

**Comment by UInt2048** [comment]
You could install the [TestFlight beta](https://testflight.apple.com/join/Fijye2AA) and see if you're still having issues.

**Comment by davidsansome** [comment]
There's a new version (1.23) rolling out this week that should fix these sync issues. Open https://tsurukame.app on your mobile to see if there's an update!
