### ISSUE TITLE
Lesson quiz not handling hard keyboard correctly on iOS 15

### ISSUE THREAD

**Issue by ficusk** [davidsansome/tsurukame#527]
I just upgraded to iOS 15 on my iPad Pro (w/ smart folio keyboard) and the quiz at the end of each lesson batch has gone a little wonky. The input field for answers isn’t showing (or focused) and there is no way to do text input:

![1E50CA3C-1B06-49EE-9E15-AFD20E4D85F9](https://user-images.githubusercontent.com/1130624/141685550-9496e5cb-a1be-4d4e-b21c-c9211f2d8a0b.png)

If I manually show the soft keyboard (or get it to show up by disconnecting the hard keyboard) I get an input field:

![D38B8E92-E7C6-4578-9DDB-5F1DA5249671](https://user-images.githubusercontent.com/1130624/141685570-584d6454-f845-4990-aff8-008048b2bccb.png)

And if I then hide the soft keyboard / reattach the hard keyboard I get an input field with a somewhat broken UI layout:

![3E84673E-0E74-4F22-8A91-2ECC92769C6A](https://user-images.githubusercontent.com/1130624/141685612-f4789ded-c880-4933-84d2-e6e85189d729.png)

At this point I am able to complete the quiz with the hard keyboard (it just stays in the weird layout for the rest of the quiz). So show/hide soft keyboard turns out to be a workaround.

**Comment by UInt2048** [comment]
If I were to take a wild guess, it has something to do with the iOS 15 popup in the bottom-right corner.

**Comment by ficusk** [comment]
Maybe? But that popup appears to be basically the same thing as the old keyboard button for summoning the soft keyboard etc. (That is indeed how I opened the soft keyboard while writing up this issue.)

**Comment by davidsansome** [comment]
I think I fixed this already in c709630d77c3876382cebba5bb977e0754b0c81c. Try installing the testflight beta from https://testflight.apple.com/join/Fijye2AA and see if that fixes it!

**Comment by ficusk** [comment]
Confirmed fixed, thanks!
