### ISSUE TITLE
going into review while syncing corrupts the database

### ISSUE THREAD

**Issue by bmironer** [davidsansome/tsurukame#534]
version 1.23.810
pull to refresh on the main menu
while it's refreshing (progress bar is still displayed), tap reviews (or press return)
review only display a black screen, with no way back
restart the app : all counts are zero, nothing is shown
had to delete app data and re-login to fix

**Comment by UInt2048** [comment]
Is this issue present in the latest beta, 1.23.881? (You can obtain it via the TestFlight link in the README.)

**Comment by bmironer** [comment]
yes, reproduced on ios version 1.23.881

**Comment by bmironer** [comment]
refreshing sometimes gets the data back for a while, but the pie chart do not display, and the data is gone again. until I fully delete and reinstall...

**Comment by bmironer** [comment]
Still happening on 1.23.902 ios testflight and macos own build.  (100% of the time if you tap reviews while the pink progress bar is showing)
Somehow fixes itself after reloading or restarting and doesn't seem to corrupt the db anymore
Also, could it be related to iCloud data syncing ? it seems it can sometime 'spread' from a device to the other (trying to isolate that one)

**Comment by davidsansome** [comment]
It takes about an hour for commits to get to TestFlight - I think it'll be fixed as of 9 minutes ago in 1.23.903.

**Comment by bmironer** [comment]
ah right, I was missing the last 2 commits. I got the full screen overlay now.
