### ISSUE TITLE
Detailed View Item Type Display Removed

### ISSUE THREAD

**Issue by UInt2048** [davidsansome/tsurukame#536]
@davidsansome

In 3e2b5831c58e125afcd3c278005affa7f4fef078, the ability to see the number of reviews that are radical, kanji, and guru were removed.

Can this please be added back in?

**Comment by davidsansome** [comment]
Sorry for the late reply!

I didn't think that was very useful as its own setting - especially at the top of the main settings view (it would've been ok as a toggle in the upcoming reviews VC itself).

I've changed it so it always shows both, and added some colours to help explain what the numbers mean:

![simulator_screenshot_B1C73BFC-1FE9-407E-A50B-9A2381F2132D](https://user-images.githubusercontent.com/314463/147872383-360eb50c-71d2-423a-a55c-0171757c8c6b.png)

What do you think?

**Comment by UInt2048** [comment]
@davidsansome Perfect, I like this! 

By any chance, could you review #524 and #530, or explain why they cannot be reviewed right now?
