### ISSUE TITLE
Subject detail view: add audio

### ISSUE THREAD

**Issue by davidsansome** [davidsansome/tsurukame#54]
There should probably be an option to download all the audio separately from the app itself.

**Comment by bradleyayers** [comment]
This would be great. Just to clarify, are there any existing audio features in the app?

**Comment by davidsansome** [comment]
Nope there are no audio features at the moment!
What I'm thinking would be:

1) Add an audio button to the 'Reading' line in the detail view.  That would play the audio directly from the WaniKani website, and would require you to be online.
2) Add a 'Downloads' section to the Settings view to allow you to download *all* the audio.  Options would be: download everything, download everything up to the current level + 1, download just the current level and the next level.
3) WaniKani probably won't be happy with the increased bandwidth for these bulk downloads, so I'd need to mirror the audio files on GCS.
4) Detect users who listen to the audio frequently, and offer to download it for them (or maybe just do it automatically, silently).  Maybe if they listen to 5+ audio samples in a single review session.

The download + local cache stuff will also be useful for downloading custom fonts.

**Comment by sciencemanx** [comment]
Is this issue meant to be closed? Is the feature available in the app yet?

**Comment by davidsansome** [comment]
Everything's done, it's just not in a release yet.  It'll be in the next update!

**Comment by bradleyayers** [comment]
Awesome, can’t wait!
