### ISSUE TITLE
App store release

### ISSUE THREAD

**Issue by abdulajet** [davidsansome/tsurukame#540]
Wondering when the next app store release will be? The app store version is the only one available for M1 macs and doesn't have all the cool new stuff from the past few months, mainly anki mode. Thanks

**Comment by UInt2048** [comment]
@abdulajet Doesn't TestFlight exist as of macOS Monterey?

Anyways, I think David Sansome wants things to be more polished before release, see discussion at #524

**Comment by abdulajet** [comment]
The testflight app doesn't have tsurukame as an option. says it's ios only

**Comment by davidsansome** [comment]
I've pushed a new update, it should rollout gradually over this week!
