### ISSUE TITLE
No new content for over two years.

### ISSUE THREAD

**Issue by Greyfire34** [davidsansome/tsurukame#541]
I’m running into a glitch where I’m stuck on level 3 for Tsurukame. And I can’t get any new reviews either. It says 6 hrs and 19 minutes til next review. And it’s said that for months. And I’m ready to move onto new context but the app is still having issues.

**Comment by UInt2048** [comment]
@Greyfire34 Have you subscribed to WaniKani? You can check at https://www.wanikani.com/account/subscription

**Comment by Greyfire34** [comment]
I hadn’t, I didn’t realize that was necessary to continue on Tsurukame. But that would actually make a LOT of sense.
