### ISSUE TITLE
No new reviews

### ISSUE THREAD

**Issue by Lisawell1** [davidsansome/tsurukame#544]
Hi, for two days now I haven’t been receiving any new reviews on the app, however, on Wanikani there are over 300 kanji reviews waiting for me. What could be the problem here?
Thank you and best regards,
Lisa

**Comment by UInt2048** [comment]
@Lisawell1 Are you using the TestFlight version of the app? There are syncing issues, especially prominent in the current App Store version.

**Comment by Lisawell1** [comment]
@UInt2048 Where can I see that? I did not update it, though.

**Comment by UInt2048** [comment]
@Lisawell1 The README here on GitHub has a link.

**Comment by davidsansome** [comment]
There's a new version (1.23) rolling out this week that should fix these sync issues. Open https://tsurukame.app on your mobile to see if there's an update!
