### ISSUE TITLE
Offline audio does not work

### ISSUE THREAD

**Issue by AOEChamp** [davidsansome/tsurukame#545]
App version: 1.22.3
iOS 15.2.1
iPhone 13

I tried a fresh install of the app, downloaded all audio in settings, turned on airplane mode and tried to play audio. "Download audio in Settings when you're back online" is displayed when trying to play audio on any item. When connected to the internet, playback works as normal.

**Comment by UInt2048** [comment]
@AOEChamp Try the TestFlight version linked in the README

**Comment by AOEChamp** [comment]
That version works! Love the new features too. Thanks for all the hard work.
