### ISSUE TITLE
Lessons  not syncing

### ISSUE THREAD

**Issue by AngryAnkylosaur** [davidsansome/tsurukame#550]
When I complete lessons it doesn’t sync to Wanikani site. If I force a sync by pulling down, the available lessons reverts back to the number before as if I had not done them. I’ve tried both the App Store and TestFlight versions.

**Comment by davidsansome** [comment]
There's a new version (1.23) rolling out this week that should fix these sync issues. Open https://tsurukame.app on your mobile to see if there's an update!
