### ISSUE TITLE
Current TestFlight build expires on April 3, 2022

### ISSUE THREAD

**Issue by pmkane** [davidsansome/tsurukame#551]
Right now, installing TestFlight build 1.23 (898) is the only way to get a working, pre-compiled Tsurukame, due to the API mismatches in the App Store version.

Beggars can't be choosers, but if possible, it would be great to know if @davidsansome has plans to release either another TestFlight build or do an App Store release before April 3rd.

If that's not in the cards or we don't hear back, I'd be happy to do a TestFlight release, under an alternative name, so that folks who don't want to or can't compile themselves still have an option to use this amazing app.

**Comment by UInt2048** [comment]
You may want to read the discussion on #524. It's possible that there are currently private commits not yet published to GitHub.

I don't have a paid developer account, but I do have [my own builds to test](https://github.com/koraigame/koraigame) which I'll be working on in the next few days...

**Comment by pmkane** [comment]
Thanks @UInt2048.

I think it's unlikely that the current TestFlight build has any private commits.  The "What to Test" section is a list of git commit messages and they line up with the commits in master up until and including the most recent one ("Trim newlines from formatted text").

Do you plan to get a paid developer account and start releasing your fork?

**Comment by UInt2048** [comment]
@pmkane Not the TestFlight build, but locally on Sansome’s computer which none of us have seen 😉

At present, I’m not intending to pay the fee especially since App Store won’t let me support iOS 8.

**Comment by davidsansome** [comment]
Hey, sorry I've been a bit AWOL lately - I'm still here, I just haven't had a lot of time for Tsurukame.

I've just pushed a couple of commits which should refresh the TestFlight beta. There are still a few little bugs I want to fix before pushing a new stable release, but I'll try to get on that in the next couple of days.

Not sure where the idea of "private commits" came from - I usually commit stuff straight away

**Comment by pmkane** [comment]
Awesome, thanks David!  All the appreciation in the world for the work you've done on the app.

**Comment by davidsansome** [comment]
Thanks! The TestFlight build is updated now, I'll kick off an App Store release as well.
