### ISSUE TITLE
Feature request: WaniKani Extra Study mode

### ISSUE THREAD

**Issue by gsorensen** [davidsansome/tsurukame#556]
In the last month, WaniKani has introduced an extra study mode which can help with practicing recent kanji / kanji you have trouble with, without it counting against your SRS level. If this is exposed in the API, this would be a very nice addition to the Tsurukame app.

Keep up the great work on the app! :)

**Comment by UInt2048** [comment]
@gsorensen I’m afraid Extra Study doesn’t expose anything new to the API for us. However, it’s not strictly necessary since Tsurukame would in self-study mode not expose anything to WK anyways. However, this already duplicates the request in #446

**Comment by poziki** [comment]
Looks like both of these feature requests got closed? Did you decide to not implement this then?

**Comment by davidsansome** [comment]
#446 is still open, let's use that one to track this!
