### ISSUE TITLE
Odd alternative meaning for 進める

### ISSUE THREAD

**Issue by Cubetwok** [davidsansome/tsurukame#566]
The definition for 進める means when you advance “something”, rather than to advance yourself (which is 進む).

I noticed one of the alternative meanings is literally “to advance”, which…kinda defeats the purpose of differentiating both words. You could answer both with the same definition and be marked right.

It would be useful if we could toggle some of the alternative meanings. If not, then at least remove this alternative meaning so we’re forced to know which verb is transitive and which is intransitive.

**Comment by davidsansome** [comment]
+1: Tsurukame just uses the data provided by Wanikani, we don't modify it at all. I'd suggest posting on the Wanikani forum instead!
