### ISSUE TITLE
Bug: Top of meaning/reading page is cut off on new iPhone models

### ISSUE THREAD

**Issue by jakepresent** [davidsansome/tsurukame#587]
As can be seen in these pictures. I’m on an iPhone 14 Pro. This happens after getting something wrong.

![2C03A2E7-858F-4EAE-81DF-B665F4360881](https://user-images.githubusercontent.com/31285242/190916671-1de3f85f-1a02-4856-852d-a31e43d9dc66.jpeg)

![E0E994E1-6242-429C-BBE5-4C8D1D7C1F0A](https://user-images.githubusercontent.com/31285242/190916955-af21be33-db1d-4194-bbc5-d7e99a6e5141.png)

**Comment by indirect** [comment]
The reviews screen also fails to fill the screen all the way down to the keyboard on an iPhone 14 Pro.

![34C80A9E-2E80-43CC-A02C-88672683F414](https://user-images.githubusercontent.com/78/191168426-8d4d5b7a-ad99-44eb-ae5a-214be9a91d27.png)

**Comment by AtahanGit** [comment]
I’m having the same issue too, it’s really annoying
![87181239-1E1E-4D71-B6F0-C65ABBD4FF29](https://user-images.githubusercontent.com/76249120/194729443-f9d3ad9d-335a-4eb0-bd9d-f01c2613c195.jpeg)

**Comment by Merman77** [comment]
Why is this issue not fixed? Developer does not reply to any e-mails.

**Comment by AtahanGit** [comment]
> Why is this issue not fixed? Developer does not reply to any e-mails. 

I know, the issue was let out 3 months ago as well. Being an iPhone 14 Pro user, I can understand frustration building on everyone with having to scroll down a little just to see the full text.

**Comment by Merman77** [comment]
If it were only a matter of: ‘having to scroll down a little’ then it would be easy to overcome. In this case you cannot scroll down, the text remains barely readable because it is cut in half. No scrolling will fix this. Please look into this issue asap!

**Comment by davidsansome** [comment]
This was fixed already in abca26167a344dbdeb89cb83ef05033e23fabb5f, it just hasn't been released to the app store yet. You can try the TestFlight beta which should have the fix: https://testflight.apple.com/join/Fijye2AA
