### ISSUE TITLE
Feature request: in Anki back to back mode combine reading and meaning review

### ISSUE THREAD

**Issue by brentlongstaff** [davidsansome/tsurukame#594]
In Anki mode I always see the kanji, say the meaning and reading to myself, and then I have to mark it right twice. There should be an option to see both reading and meaning together and mark them both right at once.

**Comment by mohitchugh** [comment]
Love the combined reading and meaning but I can’t seem to get the audio to play automatically. Is that expected? If yes, can we have a setting to play it as one selects the answer? Thanks.
