### ISSUE TITLE
Info not syncing to Wanikani when in Anki mode

### ISSUE THREAD

**Issue by vanpiro** [davidsansome/tsurukame#595]
i discovered that If I do reviews in anki mode (without typing the answers, after just a couple of times, many of the reviews i did will never sync with Wanikani. 
This does not happen when I am not in anki mode.

could you please fix this issue?

**Comment by santialbo** [comment]
This happens when you go faster than the answer slide animations. If you go slower than the animations then the answers do count. I will upload a video tomorrow showing it.

**Comment by santialbo** [comment]
Here's the video https://www.veed.io/view/43b04dac-0c60-465e-bd1e-c468ddad6d71

**Comment by vanpiro** [comment]
Thanks
I figured out how to make sure it gets the credit of the review.

happy new year

**Comment by santialbo** [comment]
Tagging @UInt2048, does this make sense? If you don't let the animations finish the answer won't be synced on Wanikani. It takes a full-refresh for tsurukame to realize. You can see a video showcasing the bug https://www.veed.io/view/43b04dac-0c60-465e-bd1e-c468ddad6d71

**Comment by UInt2048** [comment]
Thanks for the video. I call this the negative one correct answers bug. Basically, Anki mode normally always marks your answer wrong (+1 incorrect) and then reverses it before submission (-1 incorrect). But if you manage to get that popup without the answer displaying, the answer is not marked wrong, and you get a free -1 correct.However, a submitted review to WaniKani telling it you got it incorrect -1 times is obviously rejected, and Tsurukame refreshes to find out that the review is still available.iPhoneから送信2023/01/04 3:30、Santi Albo ***@***.***>のメール:﻿
Tagging @UInt2048, does this make sense? If you don't let the animations finish the answer won't be synced on Wanikani. It takes a full-refresh for tsurukame to realize. You can see a video showcasing the bug https://www.veed.io/view/43b04dac-0c60-465e-bd1e-c468ddad6d71

**Comment by santialbo** [comment]
If there is no easy way to fix this, could we at least make it so that you cannot tap the screen until the animation has finished?

**Comment by UInt2048** [comment]
@santialbo Could you please build the commit 62e28a1 to see if that works?

**Comment by santialbo** [comment]
I'm just a regular user of the app :S I don't know how to build it and test it.

**Comment by marciska** [comment]
I tried testing it. Not sure if I did the correct thing, so take everything with a grain of salt. I checked out the commit 62e28a1, but it took me a while to get the simulator running on my Mac. I never worked with Xcode before.

First off: I pressed everything as quickly as possible, but it did not prevent the menu from opening. After re-syncing with the WK server, I still found the same items re-appearing.
However, it often happened that the menu appeared without the answer being shown at all:
<img width="399" alt="Screenshot 2023-05-13 at 13 28 03" src="https://github.com/davidsansome/tsurukame/assets/59295964/ea1ef4e9-f07c-41ca-b89f-6fadb2e96140">

**Comment by tarcisiotm** [comment]
Hi, I know it has been a while since the last message on this issue, but I ran into this issue this week when I started using Anki mode, and to my surprise, I found the project was available on GitHub, so I opened a [Pull Request](https://github.com/davidsansome/tsurukame/pull/657) to fix it. The discussion in this thread helped me look in the right direction.

If anyone tests that and finds any issues, or if the code is not up to the standards, please let me know and I'll try to address it.

I have been testing this fix for about a day or so, with more than 100 reviews, and I had zero items return to my queue. I also tested regular, non Anki mode, for regressions.
