### ISSUE TITLE
Meaning cut off on IPhone 14 pro

### ISSUE THREAD

**Issue by TevDawg** [davidsansome/tsurukame#609]
![7A0A48F7-B193-4281-A2E1-A65EB0BA3D1D](https://user-images.githubusercontent.com/124664716/217186053-8fbe0746-9888-4866-a729-416ba598cf03.png)

Hi! Sorry don’t use GitHub - I’m having an issue with the app on my iPhone 14 pro (6.1 inch screen). I can’t see the “meaning” area as in the photo I’m right at the top of the scroll bar. Could this be fixed please? Thanks a bunch for the awesome app

**Comment by UInt2048** [comment]
Have you tried the TestFlight version linked in the README? I believe this issue has been solved alreadyiPhoneから送信2023/02/07 2:03、TevDawg ***@***.***>のメール:﻿

Hi! Sorry don’t use GitHub - I’m having an issue with the app on my iPhone 14 pro (6.1 inch screen). I can’t see the “meaning” area as in the photo I’m right at the top of the scroll bar. Could this be fixed please? Thanks a bunch for the awesome app

**Comment by TevDawg** [comment]
> Have you tried the TestFlight version linked in the README? I believe this issue has been solved alreadyiPhoneから送信2023/02/07 2:03、TevDawg ***@***.***>のメール:﻿ Hi! Sorry don’t use GitHub - I’m having an issue with the app on my iPhone 14 pro (6.1 inch screen). I can’t see the “meaning” area as in the photo I’m right at the top of the scroll bar. Could this be fixed please? Thanks a bunch for the awesome app —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

I haven’t! Thanks for that, I’ll give it a go now 😊

**Comment by Merman77** [comment]
But it has expired now. So here we are with a useless app.

**Comment by TevDawg** [comment]
> Have you tried the TestFlight version linked in the README? I believe this issue has been solved alreadyiPhoneから送信2023/02/07 2:03、TevDawg ***@***.***>のメール:﻿ Hi! Sorry don’t use GitHub - I’m having an issue with the app on my iPhone 14 pro (6.1 inch screen). I can’t see the “meaning” area as in the photo I’m right at the top of the scroll bar. Could this be fixed please? Thanks a bunch for the awesome app —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

Worked perfectly, thank you!

**Comment by Merman77** [comment]
As I also stated above: the beta expired. We have been 10 months without an update of the alpha.
