### ISSUE TITLE
Show all doesn't show all

### ISSUE THREAD

**Issue by rogerburkhard** [davidsansome/tsurukame#61]
Hi! I really love your Tsurukame App so thanks a lot for that. Currently I have the problem that I would like to see all my unlocked Radicals, Kanji and Vocabulary but when I tap on the "Show all" Button I only see the ones from my current level. It would be great if I could switch the levels there or just scroll trough all my learned radicals, kanjis and Vocabulary. Thanks a lot!

**Comment by davidsansome** [comment]
You can swipe left and right in that screen to go back and forward between levels!
I should improve the UI to make that more obvious!

**Comment by rogerburkhard** [comment]
Oh wow, that's awesome! I really didn't think about that! 
Thanks a lot and greetings from Switzerland!
