### ISSUE TITLE
Upcoming reviews displayed as decimals 

### ISSUE THREAD

**Issue by darkhelmet9** [davidsansome/tsurukame#614]
Hi,
I recently noticed that the upcoming review numbers are displaying as decimals instead of integers. Nothing experience breaking but I suppose it is harder to read.

![0E11E058-DC30-4B67-91F3-1DD6C0ECCF58](https://user-images.githubusercontent.com/23283846/220258492-45876384-90e8-4fd4-883f-1aef5e4995b3.jpeg)

**Comment by Xrampino** [comment]
Same here. Trying to help, just an idea: Shouldn't `barDataSet.valueFormatter` be set after the `BarChartData(dataSet: barDataSet)` here ?

https://github.com/davidsansome/tsurukame/blob/2cf2de5cccc82052eee681d4d0dd4e0a158c3264/ios/UpcomingReviewsChartItem.swift#L137-L144

As per :

https://github.com/davidsansome/tsurukame/blob/2cf2de5cccc82052eee681d4d0dd4e0a158c3264/ios/CurrentLevelChartItem.swift#L211-L213

**Comment by mlflr** [comment]
@Xrampino You are right. I created a pull request #620 for it.

**Comment by glaserL** [comment]
Just browsing, this can be closed right?
