### ISSUE TITLE
Crash when opening the app

### ISSUE THREAD

**Issue by plugerar** [davidsansome/tsurukame#619]
I have an iPhone SE with iOS version 12.2. I updated to the most recent release available on the App Store, and now I am unable to use the app. Whenever I open it, it crashes within a couple seconds. I was able to open it in airplane mode, but the app would crash as soon as I connected my phone to the internet. I tried reinstalling the app, and it is fine with the login screen, but as soon as I log in it crashes immediately.

I have the local-cache.db from before I reinstalled the app if that helps.

**Comment by AnotherBlob** [comment]
I have the same issue on iOS 12.5.7.

**Comment by esoxtim** [comment]
Same for me. Iphone 6 IOS 12.5.7
