### ISSUE TITLE
Feature request: font size context sentences 

### ISSUE THREAD

**Issue by philippefraser** [davidsansome/tsurukame#624]
Hi

I have been using your Tsurukame app for WaniKani for a while. I’m on level 8 now. 

First of all, thank you for a great app. It’s made WaniKani a joy to use on the iPhone. I especially love how it changes keyboard between Japanese and English answers. The layout and flow are smooth. 

However, as a 46 year old, I’m struggling to read the context sentences. The Japanese context sentences, the font is just too small for me. Even with my reading glasses. 

To be honest even the English font could be a bit bigger throughout!

Perhaps a settings option?

Just a request!

Kind regards

Philippe

**Comment by tallerasaf** [comment]
@philippefraser Same as: [Feature Request - Accessibility Font Size Support](https://github.com/davidsansome/tsurukame/issues/601)
