### ISSUE TITLE
Api invalid

### ISSUE THREAD

**Issue by Ksuthermoto** [davidsansome/tsurukame#628]
Invalid api error
I downloaded Tsurukame today to my iPad and initially had it working. But now I get the above error.
Still works on my iPhone.

**Comment by UInt2048** [comment]
Can you try using the TestFlight build (see the README)?

Also check your API keys are good on the WaniKani website.

**Comment by Ksuthermoto** [comment]
Many thanks, seems to be again now for me. I think it was just an error with the api key I was copying and pasting!Sent from my iPadOn 8 May 2023, at 16:30, UInt2048 ***@***.***> wrote:﻿
Can you try using the TestFlight build (see the README)?
Also check your API keys are good on the WaniKani website.
