### ISSUE TITLE
Feature Request: Support Kana-Only Vocab

### ISSUE THREAD

**Issue by UInt2048** [davidsansome/tsurukame#629]
WaniKani [has announced](https://community.wanikani.com/t/kana-only-vocabulary-is-coming/61719) a new subject type for kana-only vocabulary, as they have no associated kanji. This is a request to support it. It's my understanding that Tsurukame would treat it as an unknown subject type and ignore it when they are introduced:

https://github.com/davidsansome/tsurukame/blob/e93e361c209b28e1dbb23f7e5cd888cdf15aa3e0/ios/WaniKaniAPI/Sources/WaniKaniAPI/Subject.swift#L186-L188

**Comment by davidsansome** [comment]
Thanks for raising this! I think the current version will crash when it sees an **assignment** with a `kana_vocabulary` subject type. I've fixed that in 8835f1c3a26e9f27d90843306632b9e759b7b821, and I've also submitted f56d990ec37409bb9ee385410e20816c97e16dfe to treat `kana_vocabulary` the same as `vocabulary` but without readings. I don't know whether that'll match what the real Wanikani site does with these new vocab types yet, but it's a start.

I'll do a release to the app store today.

**Comment by marciska** [comment]
Wow this is amazing, thank you so much! I think you are not anymore using WaniKani (or at least not that active in the community anymore as you used to be), so keeping Tsurukame updated is really nice of you. Also the recurring developer fee is not to be forgotten...
Is there a way to support your work for a small thanks, like, do you have a Ko-Fi page or anything?

**Comment by davidsansome** [comment]
Thanks @marciska, I appreciate it! You're right I don't really use WaniKani any more, but I hope to come back to it one day. In the mean time I'll try to keep the app at least functional if I can.
Accepting donations is too much of a hassle, please give to another worthy charity of your choice if you really want to!

This app store update is still waiting for review from Apple, hopefully it'll be ready before Wanikani release the Kana-only vocab next Wednesday.
