### ISSUE TITLE
Wanikani syncing error?

### ISSUE THREAD

**Issue by Satrowbridge** [davidsansome/tsurukame#630]
Hi there,

I have been having an issue getting my Tsurukame to sync to Wanikani; it was previously working and, suddenly today it said I had N/A lessons and no data.

I tried resyncing, logging in and out, uninstalling the app and reinstalling it, and restarting my phone. This is a picture of what is going on.

All my data on Wanikani is on the website… so I don’t know what’s going on. Attached is a photo of what I am looking at when I log in.
![IMG_2962](https://github.com/davidsansome/tsurukame/assets/133176218/ddb413a8-30cd-4d70-91be-24714ee0180c)

any idea what I can do to fix this? Thanks. I am on iOS 16.4.1

**Comment by marksands** [comment]
Same thing is happening to me.

**Comment by nfbreen** [comment]
This is very likely a temporary problem on the Wanikani side; it seems that they have several broken API endpoints starting in the past ~4 hours, affecting all third-party apps.  If so, nothing to be done until the WK team corrects the issue.

**Comment by marksands** [comment]
I haven't looked into it (would normally love to provide more detailed info for bug reports!), but I built locally from 3 commits ago (e93e361c209b28e1dbb23f7e5cd888cdf15aa3e0), on a new install, and it's working for me on my device.

**Comment by davidsansome** [comment]
This was an issue with the WaniKani API, see https://community.wanikani.com/t/api-issues-resolved-%E2%9C%85/61801
