### ISSUE TITLE
Gravatar Image Not Loading

### ISSUE THREAD

**Issue by bachmacintosh** [davidsansome/tsurukame#635]
For some reason, Tsurukame is no longer loading my Gravatar from the email I use to log into WaniKani.

# Reproduction Steps

1. Uninstall Tsurukame if it's currently installed, and reinstall latest TestFlight Build
2. Restart iPhone
3. Sign into WaniKani in the app; the email address I use to sign in is *formatted* as `string.string@example.con`, I can provide an actual email to test if needed, but would prefer to do so privately.

## Expected Outcome 

The top-left icon in the app's main screen shows my [Gravatar](https://s.gravatar.com/avatar/cf832913d2b7c5ced15cf298839f64ee?s=80)

## Actual Outcome 

The default image displays instead of the Gravatar

![image](https://github.com/davidsansome/tsurukame/assets/3395010/2e281ef3-118f-4f68-bc71-c29322b2e492)

Let me know if any more info is needed.

Thanks!

**Comment by Deadpikle** [comment]
@bachmacintosh Seems fixed per #680 and #681. Please try the latest TestFlight build! 😄
