### ISSUE TITLE
TestFlight Beta not updated to latest commit

### ISSUE THREAD

**Issue by tallerasaf** [davidsansome/tsurukame#646]
"The TestFlight beta which is updated automatically any time there's a commit to this Git repository."

@davidsansome why the TestFlight beta is not updated?

Supposed to be version 1.29-976 but still version 1.28-972

![image](https://github.com/davidsansome/tsurukame/assets/14837253/0fdec967-0550-4b3f-89a1-1f2d49c84cf8)

**Comment by davidsansome** [comment]
Looks like it's waiting for App Store review from Apple - they do a manual review for TestFlight builds any time I increment the version number.

It'll probably take a couple of days given the long weekend in the US.
