### ISSUE TITLE
"Allow cheating" does not allow to add synonyms

### ISSUE THREAD

**Issue by tallerasaf** [davidsansome/tsurukame#647]
If I turned on "Allow cheating" I am not able to add User Synonyms but on the "Allow cheating" description it says: "Ignore Typos and Add Synonym".

**Comment by UInt2048** [comment]
Are you using Anki mode? The “add synonym” option needs to be fixed to provide an input for a synonym to be added.

**Comment by tallerasaf** [comment]
> Are you using Anki mode? The “add synonym” option needs to be fixed to provide an input for a synonym to be added.

@UInt2048 without using the Anki mode.

**Comment by UInt2048** [comment]
If you’re not in Anki mode, tap on the plus button after you type in a *meaning* answer and it will add what you typed as a synonym when you hit the “add synonym” button that will appear.

If you use Anki mode, this interaction probably needs to be fixed to give you an input for you to type the synonym you want added.

iPadから送信
