### ISSUE TITLE
Review notification number inaccurate

### ISSUE THREAD

**Issue by steakfryday** [davidsansome/tsurukame#65]
It used to only update exactly on the hour, but in the past week it’s been posting notifications of existing reviews PLUS however many are coming in the next hour. For example, I may have only 30 items to review, but it will say 50 because it’s adding in 20 future/next-hour items. I’ve uninstalled/reinstalled and turned off auto-detect for timezones. Is anyone else experimenting this?

**Comment by sciencemanx** [comment]
Ditto. I've also noticed that this app's number lags behind similar apps badge updates.

**Comment by davidsansome** [comment]
I've seen this too, I'll take a look.

**Comment by davidsansome** [comment]
This should hopefully be fixed by 00671bce615dd19a12fff5e551492280779d129b
