### ISSUE TITLE
Ability to Enable Sound Notifications

### ISSUE THREAD

**Issue by horaciohall** [davidsansome/tsurukame#650]
Hello, I'm using an iPhone 14 Pro, iOS version 16.5.1 (c) and I have been looking for a way to **turn on ringtone sound notifications** for Tsurukames review notifications. I currently find myself missing the notifications because of the lack of notification sound and then get stuck reviewing about 3 or 4 review piles when I finally notice I have a review.

Thanks for making such an amazing study tool!

**Comment by tallerasaf** [comment]
#651
