### ISSUE TITLE
App crashes while reviewing certain radical

### ISSUE THREAD

**Issue by W247** [davidsansome/tsurukame#658]
Hello,

I don’t know whether this is the correct place to post this but I’ve noticed app crashes every time the „saw“ radical comes up for review. 

I’m on iOS 16.6.1

**Comment by UInt2048** [comment]
I wonder why. I checked the Content Updates, but it’s not mentioned that anything changed…2023/09/12 4:19、W247 ***@***.***>のメール:﻿
Hello,
I don’t know whether this is the correct place to post this but I’ve noticed app crashes every time the „saw“ radical comes up for review.
I’m on iOS 16.6.1

**Comment by wjbabicz** [comment]
Same issue here -- started experiencing this yesterday, think it came up in my lessons the day prior.
