### ISSUE TITLE
App crashes when clicking on reviews

### ISSUE THREAD

**Issue by Afsy1** [davidsansome/tsurukame#662]
App crashes when trying to open reviewed on iPhone. Almost every time now.

**Comment by davidsansome** [comment]
Duplicate of #658

**Comment by UInt2048** [comment]
@Afsy1 You can get the fix by installing TestFlight build 981 or newer

**Comment by Afsy1** [comment]
For iPhone? How will this all help the issue?

**Comment by UInt2048** [comment]
@Afsy1 There’s a [TestFlight beta](https://testflight.apple.com/join/Fijye2AA) of Tsurukame that has the fix available to test
