### ISSUE TITLE
Text cut off at top bar

### ISSUE THREAD

**Issue by rfdat** [davidsansome/tsurukame#670]
![1](https://github.com/davidsansome/tsurukame/assets/130133129/d64ed4fc-85e6-41c1-abc5-2bd4ba8b81f2)

Text seems to be cut off for me at the top bar on an iPhone 13 mini iOS 17.1

**Comment by alistairvu** [comment]
Text is also cut off for me. I'm using an iPhone 15 Pro Max on iOS 17.2.

**Comment by davidsansome** [comment]
I think 4369ee6e2702bd12bbf8b36b178fe7527e3cf6e0 probably fixed this!
