### ISSUE TITLE
Input field covered by keyboard

### ISSUE THREAD

**Issue by Lilalas** [davidsansome/tsurukame#68]
I recently downloaded Tsurukame on my iPhone SE (which has a 4 inch display). It is not really usable because the text input field is almost entirely covered by the keyboard.

There is no way to scroll or hide the keyboard. It is only possible to guess what you have entered.

<img src="https://user-images.githubusercontent.com/10713547/48675965-edda7800-eb57-11e8-9aba-84c636c1e193.PNG" alt="screenshot" width="320" height="568">

**Comment by davidsansome** [comment]
I fixed this recently (issue #35) but it hasn't been released yet.  I'll try to upload a new build to the app store soon!

**Comment by Lilalas** [comment]
I can confirm, the issue got fixed in release 1.7. The content now automatically adapts to the height of the keyboard.
