### ISSUE TITLE
Score suddenly changing

### ISSUE THREAD

**Issue by philippefraser** [davidsansome/tsurukame#686]
Hi

The cumulative score at the top right of the test screens does not match the score on the final score page. 

In my example my score shows as 83% then after answering the final question correctly it changes to 65%
![IMG_0806](https://github.com/davidsansome/tsurukame/assets/78761662/1abf55cf-c412-4863-826e-3f098cbe2cfd)
![IMG_0805](https://github.com/davidsansome/tsurukame/assets/78761662/242112d2-2b60-4700-a4aa-c5ac7ce80a43)

**Comment by Deadpikle** [comment]
See #656.

> There are actually two accuracy percentages — the accuracy percentage during reviews and the accuracy percentage at the end in the review summary.
> 
> I believe Tsurukame behavior is consistent with the website if I remember correctly,
