### ISSUE TITLE
TestFlight crash when opening recent mistakes review

### ISSUE THREAD

**Issue by Deadpikle** [davidsansome/tsurukame#688]
My app crashed when I opened up the Recent Mistakes review queue from the main menu, I believe while the app was syncing. I could not replicate the crash and have not experienced it since that time.

I submitted the crash report via TestFlight. Is there any chance that the submitted crash reports for recent TestFlight builds could be checked and posted here? I'd be happy to fix the issue if it's related to the features I've added recently. It's probably something simple. At least, one can always hope.

**Comment by Motifier** [comment]
I've had the same thing happen to me and it keeps happening when i reopen the app. I've exported the local database if that would be off any use?

**Comment by Deadpikle** [comment]
This happens because `LocalCachingClient.getAllRecentMistakeAssignments` is unexpectedly finding `nil` in the line: `ret.append(cursor.proto(forColumnIndex: 0)!)`. When assignments are deleted but before they are synced again, `a.pb` is `nil`, so this function throws an error and the app crashes until it syncs properly.

See #678 for a related discussion.
