### ISSUE TITLE
App crashes at level4 

### ISSUE THREAD

**Issue by Andre145145** [davidsansome/tsurukame#698]
The app crashes at level 4. Or at least it won’t give me any new lectures from level 5. 
It also does not show my the pie charts of the current level anymore. 

It might be similar to problem 636. する is also in level 4. 
I got an iPhone 7, so it’s quite old. Maybe that’s one reason. 
Thank you for this amazing app. It kinda replaced Instagram with learning Japanese vocabulary which I find very nice. 😁

**Comment by UInt2048** [comment]
Somehow I missed this issue, but I'm guessing you figured out you have to subscribe to WaniKani in order to get paid content.
