### ISSUE TITLE
WaniKani Content Overhaul

### ISSUE THREAD

**Issue by gavia** [davidsansome/tsurukame#70]
Just in case this hasn't hit your radar, WK are overhauling their content in like 16 hours. A new database may need to be generated and updated.

https://community.wanikani.com/t/wanikani-content-overhaul-announcement/33956

**Comment by davidsansome** [comment]
Thanks!  I saw it.
Looks like it might be a bit more complicated than just updating the database though - for example:

> There will be an option to view old mnemonics (containing old radicals) in your user settings. Then you’ll be able to toggle between them during lessons, reviews, and on item pages

I'd like to support that in Tsurukame as well if I can.

I'll see what the update is actually like when it's released tomorrow, then I'll be able to start working on whatever new features are needed.
