### ISSUE TITLE
Formatting error in vocabulary lesson 活躍

### ISSUE THREAD

**Issue by mgehring** [davidsansome/tsurukame#702]
There is a typo-related error in the formatting of the vocabulary meaning text. See screenshot. ![IMG_0198](https://github.com/davidsansome/tsurukame/assets/6111649/4ceb02c6-49a4-41e6-9a14-b330118d8c35)

**Comment by UInt2048** [comment]
This is most likely a tag error on WaniKani itself (even if it handles the failure gracefully) and should be reported to WaniKani.

**Comment by davidsansome** [comment]
Yep this is a issue with the WaniKani markup. I've reported similar ones before by emailing hello@wanikani.com and they've fixed them pretty quickly. @mgehring: would you be able to report this one for me?
