### ISSUE TITLE
MacOS: Text input gets highlighted during reviews

### ISSUE THREAD

**Issue by nomonoma** [davidsansome/tsurukame#706]
After maybe the first half a second or so of a review being open, whatever text you have typed gets highlighted. If you are continuing to type that initial input gets deleted. 

See video.

https://github.com/davidsansome/tsurukame/assets/166666244/fddeedd6-ca5e-415d-bd8d-681aadf96c64

**Comment by greenburai** [comment]
I'm also having this problem. I've tried uninstalling but no fix.

**Comment by alterux** [comment]
Same problem here.
