### ISSUE TITLE
Prioritize earlier levels better please

### ISSUE THREAD

**Issue by kaydenpmd** [davidsansome/tsurukame#716]
There's an option to prioritize current level, but whatever order is picked for learning radicals-kanji-vocabulary still comes first. For example, I still have basically all level 8 vocabulary to learn, but the app is already starting me on level 9 radicals since it would rather get all radicals from both levels done than get all level 8 items done. This feels less efficient because progression becomes less linear than going one level after the other. I'm also using the apprentice limit feature to pace my lessons, so I get alot built up from multiple levels, so alot of items from current levels are sitting in the lesson queue that I could be doing instead of doing the next level.
![image](https://github.com/davidsansome/tsurukame/assets/73806300/4acddd8a-55df-4d35-b9a2-b988c8cd61cf)

**Comment by UInt2048** [comment]
Turn off prioritize current level. The name of this setting was chosen before the "current level" and "next level" graphs were split, so the word "current level" there refers to the level in the top blue navigation bar (the "next level" 9 in your case).

**Comment by kaydenpmd** [comment]
thanks that works
![image](https://github.com/davidsansome/tsurukame/assets/73806300/34dea5fd-a06a-4bac-ad82-3b316e9a08e8)

**Comment by UInt2048** [comment]
@kaydenpmd You might want to close this issue then
