### ISSUE TITLE
Problem with radical display in 景 meaning explanation

### ISSUE THREAD

**Issue by Mikomii** [davidsansome/tsurukame#717]
I don’t think I saw this in any recent issues posted.

 The meaning explanation for 景 doesn’t show the word for the radical “capital” and instead just shows “/capital” with the rest of the words in blue. Picture attached as example. It shows up in review and in the search of the kanji.

![IMG_4829](https://github.com/davidsansome/tsurukame/assets/50258285/72bcf4c5-3114-4449-9f91-8b520248fe16)

**Comment by davidsansome** [comment]
This looks like an issue with the WaniKani markup. Do you think you could report this by emailing hello@wanikani.com? They're usually pretty responsive.

**Comment by Mikomii** [comment]
Sure!
