### ISSUE TITLE
Bug: WaniKani tab does not update

### ISSUE THREAD

**Issue by Deadpikle** [davidsansome/tsurukame#729]
Hi,

Just started using the latest version that has the tab view controller. Looks like the graphs and numbers aren't refreshing after reviews are done (recent mistakes, apprentice count, recent lessons, etc). Numbers also don't refresh after doing lessons via the lesson picker. So perhaps the view updates aren't being propagated somehow. At least it's easy to replicate!

Thanks!

Edit: looks like even a full refresh does not update the page items. The reviews cell also does not update even when you have reviews. Only option is to kill the app and restart it.

**Comment by davidsansome** [comment]
Ah oops, I think I know why that's happening - I'll try to fix it later today!
