### ISSUE TITLE
Cannot level up (frozen at 3d9h)

### ISSUE THREAD

**Issue by Shs343** [davidsansome/tsurukame#732]
Hi
First thank you for all your work making the app. 
unfortunately I’ve run into an issue where I am stuck at level 3 for maybe 2 weeks where it just says next level up is in 3 days and 9 hours. No matter if I get all the items correctly. I am perpetually stuck there. It says I’m at level 4 but I have not seen any level 4 kanji. Was hoping this would resolve itself but I think it’s stuck. 
If you could help I would really appreciate it
Thanks
Shs343

**Comment by davidsansome** [comment]
Do you have a paid WaniKani subscription? Level 4+ is only available to paid members: https://www.wanikani.com/account/subscription

The app deliberately doesn't mention anything about this to avoid raising any eyebrows from Apple during App Store reviews.
