### ISSUE TITLE
Cannot sign in

### ISSUE THREAD

**Issue by drydenb** [davidsansome/tsurukame#738]
Just downloaded Tsurukame today and I cannot sign into the app with my username / password. It says: "API token not found."

Expected:
User can sign in with username / password without any other information.

Reproduce: 
Try to sign in with whatever version was pushed to the App Store July 13th 2024

**Comment by davidsansome** [comment]
Whoops sorry about that. WaniKani changed their settings page again which broke the app for new users.

You should be able to get the fix now by installing the [TestFlight beta](https://testflight.apple.com/join/Fijye2AA). I'll start releasing a new version to the App Store now as well.
