### ISSUE TITLE
App crashes at startup after content overhaul

### ISSUE THREAD

**Issue by deadperfect** [davidsansome/tsurukame#74]
The app now crashes every time it is launched, following opting in to the new radicals as part of this morning's content overhaul.

**Comment by Rion-Kaneshiro** [comment]
Crashes for me, too. Didn't click any button...

**Comment by deadperfect** [comment]
> Uh oh that's bad - I'll take a look ASAP.
> Did you click the Relearn button on https://www.wanikani.com/tools/dorc/form_tfg42 for **all** the radicals?

Yes, I selected all of the radicals.

**Comment by hesch** [comment]
Looks like it tries to load the new radicals from the offline database and crashes because it can't find them (to the app they look like entirely new items). To fix it the database just needs to be rebuilt and the app resubmitted to the App Store. I think...

**Comment by davidsansome** [comment]
Thanks.  I've found the problem - the app is crashing when it sees you have a lesson for one of the newly added radicals that isn't in the app's database yet.  I'm updating the database now.  Once that's done I'll push an update to the App Store.

**Comment by davidsansome** [comment]
Ha @hesch we both commented at the same time :) You're absolutely right.

**Comment by hesch** [comment]
Do you know how long apple will take to review the update?

**Comment by davidsansome** [comment]
Usually 1-2 days, but I've had them drag it out for a week before...

**Comment by davidsansome** [comment]
Yeah I'll post a TestFlight invite link here when the database update finishes.

**Comment by davidsansome** [comment]
The new version is now waiting for Apple review.  Turns out the TestFlight build **also** needs Apple review, so I can't give you an invite link just yet.

**Comment by deadperfect** [comment]
I just got the app update this morning.  Thank you for fixing this so quickly!

**Comment by peterthejohnston** [comment]
Thanks so much for the fix! I can do reviews etc. now, but the app crashes when I try to look at the items from level 43 (I don't know if has something to do with that level specifically)—I open app (currently on level 44), press "Show all", and then swipe to see the previous level and it crashes.

**Comment by Rion-Kaneshiro** [comment]
That seems to be a general problem, I have the same crash on level 49 when I swipe to 48.
