### ISSUE TITLE
Review "batch size" setting is confusing

### ISSUE THREAD

**Issue by zjgoodman** [davidsansome/tsurukame#745]
Someone reported in #586 that the review batch size "doesn't work." A contributor posted [this comment](https://github.com/davidsansome/tsurukame/issues/586#issuecomment-1446375391) providing an explanation that the "batch size" doesn't actually refer to the amount of items in a review session but instead refers to the internal selection pool of items when back-to-back reviews are **disabled**.

While the extended description of the functionality is sensible, the name of this setting is causing confusion. See below for the settings view of lessons and reviews.

# Lessons
![image](https://github.com/user-attachments/assets/219adb98-66e7-40c4-92bb-ea504778e813)
# Reviews
![image](https://github.com/user-attachments/assets/62af51d5-46b7-4ec5-8418-9b1afc1cc9e8)

Because both settings are called "batch size," a user would expect both of these settings to have the same effect. When in reality they do not. For lessons, it controls the number of items that appear in a lesson session. But for reviews, it controls the internal selection pool size for non-back-to-back reviews only.

I would propose the following:
1. change the `set the review queue size` description of the "review batch size" setting to provide additional explanation of what it does
2. if back-to-back reviews are enabled, disable and/or hide the "review batch size" setting entirely
3. rename the "review batch size" setting to something else so that it does not have the same name as LESSON "batch size" despite having different behavior

**Comment by zjgoodman** [comment]
I am interested in contributing the fixes for this item

**Comment by UInt2048** [comment]
@zjgoodman This is minor enough that you can probably get a PR merged. If you choose to rename it, I might suggest renaming it to "wrap-up queue size" in the user facing name. Avoid changing the internal name of the setting so that you don't affect people's already established preferences.
