### ISSUE TITLE
displays html entities as text (eg &nbsp;)

### ISSUE THREAD

**Issue by crun** [davidsansome/tsurukame#758]
in a number of vocabulary explanations, the wanikani crew used non-breaking spaces for some reason. these display correctly on the web version but are displayed as text in the app.

![IMG_7109](https://github.com/user-attachments/assets/2c23f22b-2b5e-44c3-a3d6-9318c10badd5)

**Comment by Deadpikle** [comment]
Note to whoever works on this: Cannot replicate on simulator (iOS 17, iPhone SE 3). Can replicate on device.

**Comment by davidsansome** [comment]
I can't reproduce this on either the simulator or a real device.

Maybe the WaniKani folks fixed the markup at some point?

If you see this again, please include your device version, and also a local database file will be helpful (Settings -> Export local database).
