### ISSUE TITLE
Feature Request: Add a dark app icon

### ISSUE THREAD

**Issue by scottsimenel** [davidsansome/tsurukame#764]
With iOS 18, apps can have dark icons: https://developer.apple.com/design/human-interface-guidelines/app-icons#Platform-considerations

I quickly created a version of the existing app icon with a transparent background, which should allow for the system to apply a gradient background by default.  Please feel free to use it as is or to apply any modifications to it (could be used for the tinted icon too).

![iTunesArtworkTransparent@3x](https://github.com/user-attachments/assets/a0d7f9ce-eea3-4308-a289-804c714dcc2a)

**Comment by davidsansome** [comment]
Thanks for the icon Scott!
