### ISSUE TITLE
Back-to-back reviews disable batch size

### ISSUE THREAD

**Issue by Arzorth** [davidsansome/tsurukame#772]
Hi there!

When back-to-back option is selected in reviews settings, the batch size configuration is ignored and set automatically to 1

Regards

**Comment by Arzorth** [comment]
To make it clearer, the exact effect is that when clicking on "Wrap up" the app asks you only for one more review instead of the number it is configured in settings.

**Comment by UInt2048** [comment]
Works as intended. See #759 which attempts to explain this in the app

**Comment by Arzorth** [comment]
Should then the option batch size disappear if back-to-back is selected?
