### ISSUE TITLE
Cannot enter geoduck pronunciation 

### ISSUE THREAD

**Issue by ascii27** [davidsansome/tsurukame#781]
The current onyomi text (pink view) says to type in ペ-ジ. Unfortunately the keyboard keeps putting the hiragana character  じ　not ジ　when I type. Which won’t be accepted. If I try to replace the じ　with a copy and paste for ジ　it also won’t work. 

To give you exact steps, here is how to repeat it:
1) go to the onyomi reading for 頁.
2) type the following in romanji in the keyboard:
pe - ji 

expected: it converts to ぺ-ジ
actual: it converts to ぺ-じ

Result: you cannot pass the reading for 頁

Please help!

**Comment by fancymatt** [comment]
Looks like this was fixed 4 days ago in 394824236ddb75ed5741f5adcaad6a32a3841a1e

**Comment by ascii27** [comment]
Marking as closed since it's a duplicate. Thank you!
