### ISSUE TITLE
Anki Mode - Users unable to do Reviews

### ISSUE THREAD

**Issue by tarcisiotm** [davidsansome/tsurukame#787]
[This commit](https://github.com/davidsansome/tsurukame/commit/9ce9f39654ac436a2b7e881ea6ff5a49d4043ff2) seems to have made Anki mode unusable on Tsurukame.

Steps To reproduce:
- Enable Anki mode
- Try to do a review
- Observe: tapping won't reveal the answers, resulting in a soft lock. Users are unable to progress through their reviews.

**Comment by abdulajet** [comment]
yep same issue here
