### ISSUE TITLE
Add support for new radical names

### ISSUE THREAD

**Issue by vladh** [davidsansome/tsurukame#79]
The new radical names as part of the [content overhaul](https://community.wanikani.com/t/wanikani-content-overhaul/33972) are currently being rejected. Both (new/old) meanings should be accepted. Maybe a good idea to have a toggle as the web version does, for whether to show both readings.

![img_5359](https://user-images.githubusercontent.com/291640/49683518-c4619c00-fac6-11e8-9d5e-844d3a18a54a.PNG)

**Comment by davidsansome** [comment]
That should be fixed already!  Can you check you have the latest update installed?  It should be version 1.6 in the app store.

**Comment by vladh** [comment]
Oof, that's my bad, I totally missed the update, sorry about that!
