### ISSUE TITLE
Lessons crash app & reviews show nothing

### ISSUE THREAD

**Issue by sloansparger** [davidsansome/tsurukame#81]
Device: iPhone Xs Max
iOS Version: 12.1.1
App Version: 1.6
Screen capture of my issue: [video link](
https://www.dropbox.com/s/169v0791hwr24pd/Video%20Dec%2008%2C%2010%2053%2056%20PM.mp4?dl=0)
Steps to reproduce: Started encountering this after making the latest iOS update and updating tsurukame (so can't say which might have caused this to start). Clicking on lessons crashes the app everytime, clicking on review just shows an empty review view. The count for notifications and reviews are incorrect as well. I had zero reviews at the moment of this recording.

**Comment by sloansparger** [comment]
Oh, I should add that I deleted the app and redownload it. I had noticed there was a local database export option, so wasn't sure if the localdb had become corrupt. Guessing after redownloading that rules out that at an issue. However, I'll go ahead and attach my current one here: [local-cache.db](https://www.dropbox.com/s/5xk0afv0forxtvf/local-cache.db?dl=0)

**Comment by davidsansome** [comment]
Looking in your local database, it looks like you've hit the max level on your free WaniKani subscription:

username: "sloansparger"
level: 4
max_level_granted_by_subscription: 3

What does it say when you go to https://www.wanikani.com/account/subscription ?

The app shouldn't crash though either way.  I'll try to fix that.

**Comment by sloansparger** [comment]
Ahhhhhh that's exactly what it was! I was being told it wasn't time to upgrade yet, and the API was returning this for my user, which was throwing me off:
```
{
  "user_information": {
    "username": "sloansparger",
    "level": 3,
    ...
  },
  ...
}
```
However, I went ahead and got a subscription and this did in fact fix things and update my `level` to 4. Probably a bug I should file with WaniKani.

Thanks for helping out! Your app is amazing and I definitely prefer using it over the actual WaniKani interface. Great work and thanks for making my life easier 😄
