### ISSUE TITLE
Reviews from higher levels shown

### ISSUE THREAD

**Issue by hesch** [davidsansome/tsurukame#83]
The app shows reviews for levels higher than your current level. After the content overhaul some items were moved to higher levels. These items can't be reviewed on the website, but tsurukame shows them for review. I asked the WaniKani-Support if this is a bug on their side, but they said it was intentional and the reviews would resume when the user reaches the new level of the item.

To make the case more clear here is an example:
- I am level 30 and do a lesson for an item, that is in level 30 at this moment
- The item gets moved to let's say level 35
- After 4 hours the review shows up in Tsurukame but not on WaniKani

I'm not entirely sure this should be fixed (I mean why shouldn't you be able to review already learned items?), but it is a inconsistency between the website and the app.

**Comment by onimitch** [comment]
Maybe it could be offered as an option in settings about whether to include higher level items
