### ISSUE TITLE
Pull-to-refresh doesn't always update review count

### ISSUE THREAD

**Issue by indirect** [davidsansome/tsurukame#85]
I've seen a couple of times where using pull-to-refresh doesn't update the count of reviews that I have available... but force quitting the app and re-opening it does update the count to be correct. Is there some cache that is cleared on force-quit that isn't cleared on pull-to-refresh?

**Comment by onimitch** [comment]
Yeah I've seen this too. Happens fairly regularly

**Comment by deadperfect** [comment]
I have seen this too, particularly when I re-enable Wifi and cellular data when the app is open.  I then have to force close and re-open for it to fetch properly.

**Comment by indirect** [comment]
In my testing, this is fixed. Thanks!
