### ISSUE TITLE
Close but no cigar & disable partial answer match

### ISSUE THREAD

**Issue by onimitch** [davidsansome/tsurukame#86]
Currently it's not possible to turn off the partial matching of answers (there is an option to disable cheating but i still want to have the ignore option).

My ideal would be behaviour like the "close but no cigar" user script, where a partial correct answer notifies you that you are close, but doesn't accept the answer yet and waits for the 100% correct match.

**Comment by turtlemaster19** [comment]
Agree. Coming from AlliCrab, this is very important for things like "to rise" vs. "to raise" and "poisoning" vs. "poisonous"

**Comment by turtlemaster19** [comment]
@davidsansome, would this be too hard to implement soon for a major update?

**Comment by UInt2048** [comment]
This is now implemented as the "exact match" setting.
