### ISSUE TITLE
Search feature?

### ISSUE THREAD

**Issue by cpojer** [davidsansome/tsurukame#89]
I find myself often going to the level overview and then going back and forth to find a particular radical, kanji or vocabulary. I know I can use a dictionary but I’d prefer to search within what I have explicitly learned so far.

Is this something you’d be willing to include if I were to build it?

Questions:
* Where would you add the search bar (scrolling up on the main screen)?
* By default I think it makes sense to only look for already learned things. What about an option to search for everything in wanikani?
* How should search work? I was thinking partial word match (not fuzzy search) of meanings, readings or kanji/words written out. Does that sound good?

Let me know if this makes sense and if you have any other requests :)

**Comment by davidsansome** [comment]
Hi!

There's already a search button at the top of the main screen - in the blue area with your name and picture, next to the settings button.
Did you mean something different?

**Comment by cpojer** [comment]
Oh wow, after a month of using the app daily I somehow missed this. Embarrassing, oops!
