### ISSUE TITLE
~ doesn't show in some fonts

### ISSUE THREAD

**Issue by a-papadopoulos** [davidsansome/tsurukame#91]
In the latest update, some fonts don't support the 〜 character of some vocabulary items. As a result, some items are shown incorrectly as the version without the 〜, resulting in a wrong answer, e.g. 〜軒 (けん) vs 軒 (のき). I would imagine the easiest fix would be to always show 〜 with the default font.

**Comment by bmironer** [comment]
The repeater also doesn’t appear with some fonts.
