### ISSUE TITLE
App crashes at startup

### ISSUE THREAD

**Issue by kangaskhan** [davidsansome/tsurukame#96]
Perhaps this is an issue that has been resolved, but with my phone configuration (iPhone 6S, 64-GB) I frequently experience app crashes when starting up the app. 

I uninstalled & reinstalled the app and it started working again; however, I'm experiencing the crashes once again. 
I reinstalled again and the app works properly ... thought it might be useful to report for your data.

**Comment by Nosgoroth** [comment]
I'm having the same issue.

**Comment by SassyHijinx** [comment]
I’m having the same problem- it crashes when I open the app.

**Comment by turtlemaster19** [comment]
Yikes... Is this (or #99) still occurring?

**Comment by mzsanford** [comment]
Another crash was fixed in https://github.com/davidsansome/tsurukame/pull/266 and should now be in the App store. Maybe that fixed it?

**Comment by turtlemaster19** [comment]
@davidsansome?

**Comment by davidsansome** [comment]
This bug is quite old so the crashes are probably unrelated.
Let's close this one, and open a new bug for any future crashes.
